package com.wtm.ingest;

import com.wtm.security.AuthorizationService;
import com.wtm.security.Permission;
import java.io.*;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.time.*;import java.time.format.DateTimeFormatter;import java.util.*;

/** Builds deterministic, domain-scoped evidence before a question reaches Ollama. */
public final class OperationalContextEngine {
 public enum View { NONE, OPERATIONS, LHY, PICKS, BINNED, EXCEPTIONS, AUDIT, EQUIPMENT, TRANSPORT, UNSUPPORTED }
 public record Analysis(View view,String context,LinkedHashMap<String,String> metrics,List<String> labels,List<Double> values,List<String> sources,boolean operationalIntent){}
 private static final Path ROOT=Path.of(System.getProperty("user.home"),".northstar-operations-intelligence","operational-data");
 private static final LocalDate TODAY=LocalDate.now();
 private OperationalContextEngine(){}

 public static Analysis analyze(String question){String q=question==null?"":question.trim(),l=q.toLowerCase(Locale.ROOT);if(q.isBlank())return empty();
  if(l.contains("isn't in")||l.contains("is not in")||l.contains("not in the imported")||l.contains("outside the imported")||l.contains("make something up"))return unsupported();
  boolean lhy=has(l,"lhy","labor hour yield","labour hour yield"), picks=has(l,"pick","picker","picking"), binned=has(l,"binned","binning"), exceptions=has(l,"floor denial","shorted","undo","ticket","delete","replen","exception","quality"), audit=has(l,"who touched","trace","barcode","audit","touched item","touched location","touched task"), equipment=has(l,"rf terminal","terminal","equipment"), transport=has(l,"truck","shipment","freight","trailer","tracking","delivery","delivered","eta","transport"), broad=has(l,"how are operations","operations summary","operational issues","operational performance","how are we doing","what changed","attention to","operations performing","executive summary","today's operations","todays operations");
  try{
   if(lhy)return lhy(); if(picks)return peopleFeed(DataIngestionService.Type.HOURLY_PICKS,View.PICKS,"Picks",q); if(binned)return peopleFeed(DataIngestionService.Type.HOURLY_BINNED,View.BINNED,"Binned Tasks",q); if(audit)return audit(q); if(equipment)return equipment(q); if(exceptions)return exceptions(q); if(transport)return transport(q); if(broad)return operations(q);
  }catch(Exception e){return new Analysis(View.OPERATIONS,"CURRENT DATE: "+TODAY+"\nOperational analysis error: "+safe(e.getMessage()),new LinkedHashMap<>(),List.of(),List.of(),List.of(),true);}
  return empty();
 }

 private static Analysis operations(String q)throws Exception{StringBuilder c=new StringBuilder("CURRENT DATE: ").append(TODAY).append("\nQUERY MODE: CROSS-DOMAIN OPERATIONS BRIEF\n");LinkedHashMap<String,String>m=new LinkedHashMap<>();List<String>s=new ArrayList<>();
  Analysis l=lhy();append(c,m,s,l,"PRODUCTIVITY");Analysis p=peopleFeed(DataIngestionService.Type.HOURLY_PICKS,View.PICKS,"Picks",q);append(c,m,s,p,"PICKING");Analysis b=peopleFeed(DataIngestionService.Type.HOURLY_BINNED,View.BINNED,"Binned Tasks",q);append(c,m,s,b,"BINNING");Analysis x=exceptions(q);append(c,m,s,x,"EXCEPTIONS");
  if(s.isEmpty())c.append("No recognized operational feeds are currently loaded.\n");return new Analysis(View.OPERATIONS,c.toString(),limitMetrics(m,8),List.of(),List.of(),distinct(s),true);}

 private static Analysis lhy()throws Exception{Path p=file(DataIngestionService.Type.DAILY_PRODUCTIVITY);LinkedHashMap<String,String>m=new LinkedHashMap<>();if(!Files.isRegularFile(p))return missing(View.LHY,"Daily LHY & LPH",true);Table t=read(p);int di=t.idx("logdate","date","workdate"),li=t.idx("lhy","laborhouryield"),ini=t.idx("inboundlph"),outi=t.idx("outboundlph");List<DateVal>vals=new ArrayList<>();String latestIn="",latestOut="";for(String[]r:t.rows){LocalDate d=date(t.get(r,di));Double v=num(t.get(r,li));if(d!=null&&v!=null&&v>0){vals.add(new DateVal(d,v));latestIn=t.get(r,ini);latestOut=t.get(r,outi);}}vals.sort(Comparator.comparing(DateVal::date));if(vals.isEmpty())return missing(View.LHY,"Daily LHY & LPH has no completed LHY rows",true);DateVal last=vals.get(vals.size()-1);double recent=avg(vals.subList(Math.max(0,vals.size()-5),vals.size()));YearMonth ym=YearMonth.from(last.date);double month=avg(vals.stream().filter(v->YearMonth.from(v.date).equals(ym)).toList());LocalDate ws=last.date.minusDays(last.date.getDayOfWeek().getValue()-1L);double week=avg(vals.stream().filter(v->!v.date.isBefore(ws)).toList());m.put("Latest LHY",fmt(last.value));m.put("5-Day Avg",fmt(recent));m.put("Week Avg",fmt(week));m.put("Month Avg",fmt(month));StringBuilder c=new StringBuilder("CURRENT DATE: ").append(TODAY).append("\nDATASET: Daily LHY & LPH\nLatest completed date: ").append(last.date).append("\nLatest LHY: ").append(fmt(last.value)).append("\n5-day average: ").append(fmt(recent)).append("\nWeek average: ").append(fmt(week)).append("\nMonth average: ").append(fmt(month)).append("\nTarget: 17,500\n");if(!latestIn.isBlank())c.append("Latest inbound LPH: ").append(latestIn).append('\n');if(!latestOut.isBlank())c.append("Latest outbound LPH: ").append(latestOut).append('\n');if(last.date.isBefore(TODAY))c.append("Freshness note: latest completed productivity date is ").append(last.date).append(", not today. Do not call it today's completed result.\n");c.append("Blank LHY rows are partial/in-progress and are excluded from completed-day comparisons.\n");return new Analysis(View.LHY,c.toString(),m,vals.stream().map(v->v.date.toString()).toList(),vals.stream().map(DateVal::value).toList(),List.of(p.getFileName().toString()),true);}

 private static Analysis peopleFeed(DataIngestionService.Type type,View view,String label,String q)throws Exception{Path p=file(type);if(!Files.isRegularFile(p))return missing(view,label,true);Table t=read(p);int total=t.idx("total","totalpicks","totaltasks"),user=t.idx("completeduserbk","userbk","userid","user","shortname"),first=t.idx("firstname"),last=t.idx("lastname");List<NameVal>list=new ArrayList<>();double sum=0;for(String[]r:t.rows){Double v=num(t.get(r,total));if(v==null)continue;String n=((t.get(r,first)+" "+t.get(r,last)).trim());if(n.isBlank())n=t.get(r,user);if(n.isBlank())n="Unknown";list.add(new NameVal(n,v));sum+=v;}list.sort(Comparator.comparingDouble(NameVal::value).reversed());LinkedHashMap<String,String>m=new LinkedHashMap<>();m.put("Total "+label,fmt(sum));m.put("Active Users",String.valueOf(list.size()));if(!list.isEmpty()&&AuthorizationService.allowed(Permission.AI_EMPLOYEE_METRICS))m.put("Top User",list.get(0).name+" • "+fmt(list.get(0).value));StringBuilder c=new StringBuilder("CURRENT DATE: ").append(TODAY).append("\nDATASET: ").append(label).append(" latest imported snapshot\nTotal: ").append(fmt(sum)).append("\nRows/users: ").append(list.size()).append("\n");if(AuthorizationService.allowed(Permission.AI_EMPLOYEE_METRICS)){c.append("Top users:\n");for(int i=0;i<Math.min(8,list.size());i++)c.append(i+1).append(". ").append(list.get(i).name).append(" = ").append(fmt(list.get(i).value)).append('\n');}else c.append("Employee-level rankings are hidden because AI employee-metrics permission is not granted.\n");c.append("This feed does not necessarily contain an embedded date. If no date column exists, describe it as the latest imported snapshot rather than claiming it is today's activity.\n");List<NameVal>chart=AuthorizationService.allowed(Permission.AI_EMPLOYEE_METRICS)?list.subList(0,Math.min(8,list.size())):List.of();return new Analysis(view,c.toString(),m,chart.stream().map(NameVal::name).toList(),chart.stream().map(NameVal::value).toList(),List.of(p.getFileName().toString()),true);}

 private static Analysis exceptions(String q)throws Exception{StringBuilder c=new StringBuilder("CURRENT DATE: ").append(TODAY).append("\nQUERY MODE: EXCEPTIONS / QUALITY\n");LinkedHashMap<String,String>m=new LinkedHashMap<>();List<String>s=new ArrayList<>();Path f=file(DataIngestionService.Type.FLOOR_DENIALS);if(Files.isRegularFile(f)){Table t=read(f);int qi=t.idx("shortedtaskqty","shortedqty","qty"),vi=t.idx("extvalueshorted","extendedvalueshorted");double qty=0,val=0;for(String[]r:t.rows){Double a=num(t.get(r,qi)),b=num(t.get(r,vi));if(a!=null)qty+=Math.abs(a);if(b!=null)val+=b;}m.put("Floor Denials",String.valueOf(t.rows.size()));m.put("Units Shorted",fmt(qty));m.put("Value Exposure",money(val));c.append("Floor denials: ").append(t.rows.size()).append(" events; ").append(fmt(qty)).append(" units; ").append(money(val)).append(" extended value.\n");s.add(f.getFileName().toString());}addCount(c,m,s,DataIngestionService.Type.TASK_DELETIONS,"Task Deletion Rows");addCount(c,m,s,DataIngestionService.Type.TICKET_UNDOS,"Ticket Undo Rows");if(s.isEmpty())c.append("No exception/quality feeds are loaded.\n");return new Analysis(View.EXCEPTIONS,c.toString(),limitMetrics(m,8),List.of(),List.of(),distinct(s),true);}

 private static Analysis audit(String q)throws Exception{List<Path>files=List.of(file(DataIngestionService.Type.AUDIT_ITEM),file(DataIngestionService.Type.AUDIT_LOCATION),file(DataIngestionService.Type.AUDIT_TASK));List<String>terms=tokens(q);StringBuilder c=new StringBuilder("CURRENT DATE: ").append(TODAY).append("\nQUERY MODE: ACTIVITY TRACE\n");List<String>s=new ArrayList<>();int hits=0;for(Path p:files)if(Files.isRegularFile(p)){Table t=read(p);s.add(p.getFileName().toString());for(String[]r:t.rows){String line=String.join(" | ",r).toLowerCase(Locale.ROOT);boolean match=terms.stream().filter(x->x.length()>3).anyMatch(line::contains);if(match&&hits<40){c.append(String.join(" | ",r)).append('\n');hits++;}}}c.append("Matched audit rows: ").append(hits).append(". Keep chronology and do not invent missing steps.\n");return new Analysis(View.AUDIT,c.toString(),metrics("Matches",String.valueOf(hits)),List.of(),List.of(),distinct(s),true);}

 private static Analysis equipment(String q)throws Exception{StringBuilder c=new StringBuilder("CURRENT DATE: ").append(TODAY).append("\nQUERY MODE: EQUIPMENT / RF\n");LinkedHashMap<String,String>m=new LinkedHashMap<>();List<String>s=new ArrayList<>();addCount(c,m,s,DataIngestionService.Type.RF_TERMINAL,"RF Terminal Rows");addCount(c,m,s,DataIngestionService.Type.EQUIPMENT_USAGE,"Equipment Activity Rows");return new Analysis(View.EQUIPMENT,c.toString(),m,List.of(),List.of(),distinct(s),true);}

 private static Analysis transport(String q)throws Exception{Path p=Path.of(System.getProperty("user.home"),".northstar-operations-intelligence","truck-tracking.csv");if(!Files.isRegularFile(p)){Path tele=file(DataIngestionService.Type.TRACKER_TELEMETRY);if(Files.isRegularFile(tele))p=tele;}if(!Files.isRegularFile(p))return missing(View.TRANSPORT,"Truck/tracker data",true);Table t=read(p);LinkedHashMap<String,String>m=metrics("Tracking Rows",String.valueOf(t.rows.size()));StringBuilder c=new StringBuilder("CURRENT DATE: ").append(TODAY).append("\nQUERY MODE: TRANSPORTATION / SHIPMENT TRACKING\nTracking rows: ").append(t.rows.size()).append("\nOnly use this transport dataset for truck, shipment, trailer, carrier, delivery, ETA or tracking questions.\n");return new Analysis(View.TRANSPORT,c.toString(),m,List.of(),List.of(),List.of(p.getFileName().toString()),true);}

 private static Analysis unsupported(){List<String>loaded=new ArrayList<>();for(DataIngestionService.Type t:DataIngestionService.Type.values())if(t!=DataIngestionService.Type.UNKNOWN&&Files.isRegularFile(file(t)))loaded.add(t.name());String c="CURRENT DATE: "+TODAY+"\nThe user explicitly requested information not supported by imported/connected data. Do not invent an operational fact. Explain that NorthStar only makes claims supported by its evidence and list available data domains if useful. Loaded feeds: "+String.join(", ",loaded);return new Analysis(View.UNSUPPORTED,c,new LinkedHashMap<>(),List.of(),List.of(),List.of(),true);}
 private static Analysis missing(View v,String name,boolean op){return new Analysis(v,"CURRENT DATE: "+TODAY+"\nRequired operational feed not loaded: "+name+". State exactly what dataset is missing; do not substitute an unrelated source.",new LinkedHashMap<>(),List.of(),List.of(),List.of(),op);}
 private static Analysis empty(){return new Analysis(View.NONE,"",new LinkedHashMap<>(),List.of(),List.of(),List.of(),false);}
 private static void append(StringBuilder c,LinkedHashMap<String,String>m,List<String>s,Analysis a,String head){if(a.sources.isEmpty())return;c.append("\n[").append(head).append("]\n").append(a.context);a.metrics.forEach(m::putIfAbsent);s.addAll(a.sources);}
 private static void addCount(StringBuilder c,LinkedHashMap<String,String>m,List<String>s,DataIngestionService.Type t,String label)throws IOException{Path p=file(t);if(!Files.isRegularFile(p))return;long n=Math.max(0,Files.lines(p).count()-1);m.put(label,String.valueOf(n));c.append(label).append(": ").append(n).append('\n');s.add(p.getFileName().toString());}
 private static Path file(DataIngestionService.Type t){return ROOT.resolve(t.name().toLowerCase(Locale.ROOT)+".csv");}
 private record DateVal(LocalDate date,double value){}private record NameVal(String name,double value){}
 private static double avg(List<DateVal>x){return x.isEmpty()?0:x.stream().mapToDouble(DateVal::value).average().orElse(0);}private static String fmt(double x){return String.format(Locale.US,"%,.1f",x);}private static String money(double x){return String.format(Locale.US,"$%,.2f",x);}private static boolean has(String s,String...x){for(String v:x)if(s.contains(v))return true;return false;}private static List<String>distinct(List<String>x){return new ArrayList<>(new LinkedHashSet<>(x));}private static LinkedHashMap<String,String>metrics(String k,String v){LinkedHashMap<String,String>m=new LinkedHashMap<>();m.put(k,v);return m;}private static LinkedHashMap<String,String>limitMetrics(LinkedHashMap<String,String>m,int n){LinkedHashMap<String,String>o=new LinkedHashMap<>();for(var e:m.entrySet()){if(o.size()>=n)break;o.put(e.getKey(),e.getValue());}return o;}
 private static LocalDate date(String s){if(s==null||s.isBlank())return null;for(DateTimeFormatter f:List.of(DateTimeFormatter.ISO_LOCAL_DATE,DateTimeFormatter.ofPattern("M/d/uuuu"),DateTimeFormatter.ofPattern("MM/dd/uuuu"))){try{return LocalDate.parse(s.trim(),f);}catch(Exception e){}}return null;}private static Double num(String s){if(s==null||s.isBlank())return null;try{return Double.parseDouble(s.replace("$","").replace(",","").trim());}catch(Exception e){return null;}}private static String safe(String s){return s==null?"unknown":s.replace('\n',' ');}
 private static List<String>tokens(String q){return Arrays.stream(q.toLowerCase(Locale.ROOT).split("[^a-z0-9_-]+" )).filter(x->x.length()>2).toList();}
 private static final class Table{final String[]h;final List<String[]>rows;final Map<String,Integer>ix=new HashMap<>();Table(String[]h,List<String[]>r){this.h=h;rows=r;for(int i=0;i<h.length;i++)ix.put(norm(h[i]),i);}int idx(String...n){for(String x:n){Integer i=ix.get(norm(x));if(i!=null)return i;}return-1;}String get(String[]r,int i){return i>=0&&i<r.length?r[i].trim():"";}}
 private static Table read(Path p)throws IOException{List<String>lines=Files.readAllLines(p,StandardCharsets.UTF_8);if(lines.isEmpty())return new Table(new String[0],List.of());String[]h=csv(lines.get(0));List<String[]>r=new ArrayList<>();for(int i=1;i<lines.size();i++)if(!lines.get(i).isBlank())r.add(csv(lines.get(i)));return new Table(h,r);}private static String norm(String s){return s==null?"":s.toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9]","");}private static String[]csv(String line){List<String>o=new ArrayList<>();StringBuilder b=new StringBuilder();boolean q=false;for(int i=0;i<line.length();i++){char c=line.charAt(i);if(c=='\"'){if(q&&i+1<line.length()&&line.charAt(i+1)=='\"'){b.append('\"');i++;}else q=!q;}else if(c==','&&!q){o.add(b.toString());b.setLength(0);}else b.append(c);}o.add(b.toString());return o.toArray(String[]::new);}
}
