package com.wtm.ingest;
import java.io.*;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.util.*;
public final class OperationalAnalytics {
 private OperationalAnalytics(){}
 public static String contextFor(String question){String q=question==null?"":question.toLowerCase(Locale.ROOT);DataIngestionService s=DataIngestionService.get();StringBuilder b=new StringBuilder("VERIFIED NORTHSTAR OPERATIONAL DATA\n");try{
  if(q.contains("lhy")||q.contains("lph")||q.contains("productiv")||q.contains("operation"))summarizeProductivity(s,b);
  if(q.contains("floor denial")||q.contains("short"))summarizeFloor(s,b);
  if(q.contains("delete")||q.contains("replen"))summarizeCount(s,DataIngestionService.Type.TASK_DELETIONS,b,"Task deletion records");
  if(q.contains("undo")||q.contains("ticket"))summarizeCount(s,DataIngestionService.Type.TICKET_UNDOS,b,"Ticket undo records");
  if(q.contains("terminal")||q.contains(" rf ")||q.startsWith("rf "))summarizeCount(s,DataIngestionService.Type.RF_TERMINAL,b,"RF terminal assignment records");
  if(q.contains("equipment"))summarizeCount(s,DataIngestionService.Type.EQUIPMENT_USAGE,b,"Equipment activity records");
  if(q.contains("touch")||q.contains("trace")||q.contains("barcode")||q.contains("location")||q.contains("part")){summarizeCount(s,DataIngestionService.Type.AUDIT_ITEM,b,"Item audit events");summarizeCount(s,DataIngestionService.Type.AUDIT_LOCATION,b,"Location audit events");summarizeCount(s,DataIngestionService.Type.AUDIT_TASK,b,"Task audit events");}
 }catch(Exception e){b.append("Analytics note: ").append(e.getMessage()).append('\n');}return b.length()<45?"":b.toString();}
 private static void summarizeProductivity(DataIngestionService s,StringBuilder b)throws IOException{Path p=s.dataFile(DataIngestionService.Type.DAILY_PRODUCTIVITY);if(!Files.isRegularFile(p)){b.append("Daily productivity feed: not loaded.\n");return;}List<String[]> rows=csv(p);if(rows.size()<2)return;String[] h=rows.get(0);int lhy=idx(h,"LHY"),in=idx(h,"Inbound LPH"),out=idx(h,"Outbound LPH"),date=idxAny(h,"LOGDATE","Date");List<Double> vals=new ArrayList<>();String latest="";double latestL=Double.NaN,latestIn=Double.NaN,latestOut=Double.NaN;for(int i=1;i<rows.size();i++){String[] r=rows.get(i);Double v=num(r,lhy);if(v!=null){vals.add(v);latestL=v;latest=date>=0&&date<r.length?r[date]:"";latestIn=val(r,in);latestOut=val(r,out);}}if(vals.isEmpty()){b.append("Daily productivity is loaded but contains no completed LHY values; current day may be partial.\n");return;}double avg=vals.stream().mapToDouble(Double::doubleValue).average().orElse(0),recent=vals.subList(Math.max(0,vals.size()-5),vals.size()).stream().mapToDouble(Double::doubleValue).average().orElse(0);b.append(String.format(Locale.US,"Completed LHY days: %d; overall average %.2f; recent 5-day average %.2f; target 17500. Latest completed %s LHY %.2f",vals.size(),avg,recent,latest,latestL));if(!Double.isNaN(latestIn))b.append(String.format(Locale.US,", inbound LPH %.2f",latestIn));if(!Double.isNaN(latestOut))b.append(String.format(Locale.US,", outbound LPH %.2f",latestOut));b.append(". Blank LHY rows are PARTIAL and must not be treated as completed days.\n");summarizeCount(s,DataIngestionService.Type.HOURLY_PICKS,b,"Latest hourly pick rows");summarizeCount(s,DataIngestionService.Type.HOURLY_BINNED,b,"Latest hourly binned-task rows");}
 private static void summarizeFloor(DataIngestionService s,StringBuilder b)throws IOException{Path p=s.dataFile(DataIngestionService.Type.FLOOR_DENIALS);if(!Files.isRegularFile(p)){b.append("Floor denial feed: not loaded.\n");return;}List<String[]> rows=csv(p);if(rows.size()<2)return;String[] h=rows.get(0);int qty=idxAny(h,"Shorted Task Qty","ShortedTaskQty"),val=idxAny(h,"Ext Value Shorted","ExtValueShorted");double q=0,v=0;for(int i=1;i<rows.size();i++){Double x=num(rows.get(i),qty),y=num(rows.get(i),val);if(x!=null)q+=x;if(y!=null)v+=y;}b.append(String.format(Locale.US,"Floor denials: %d events; %.0f units shorted; $%,.2f extended value represented in current feed.\n",rows.size()-1,q,v));}
 private static void summarizeCount(DataIngestionService s,DataIngestionService.Type t,StringBuilder b,String label)throws IOException{Path p=s.dataFile(t);if(Files.isRegularFile(p))try(var lines=Files.lines(p)){long n=Math.max(0,lines.count()-1);b.append(label).append(": ").append(n).append(".\n");}}
 private static List<String[]> csv(Path p)throws IOException{List<String[]> out=new ArrayList<>();for(String line:Files.readAllLines(p,StandardCharsets.UTF_8))out.add(parse(line));return out;}private static String[] parse(String line){List<String>a=new ArrayList<>();StringBuilder b=new StringBuilder();boolean q=false;for(int i=0;i<line.length();i++){char c=line.charAt(i);if(c=='\"'){if(q&&i+1<line.length()&&line.charAt(i+1)=='\"'){b.append('\"');i++;}else q=!q;}else if(c==','&&!q){a.add(b.toString());b.setLength(0);}else b.append(c);}a.add(b.toString());return a.toArray(String[]::new);}private static int idx(String[]h,String n){for(int i=0;i<h.length;i++)if(h[i].trim().equalsIgnoreCase(n))return i;return-1;}private static int idxAny(String[]h,String...n){for(String x:n){int i=idx(h,x);if(i>=0)return i;}return-1;}private static Double num(String[]r,int i){if(i<0||i>=r.length||r[i].isBlank())return null;try{return Double.parseDouble(r[i].replace("$","").replace(",",""));}catch(Exception e){return null;}}private static double val(String[]r,int i){Double d=num(r,i);return d==null?Double.NaN:d;}
}
