package com.wtm.ai;

import com.wtm.security.AuthorizationService;import com.wtm.security.Permission;import com.wtm.util.MiniJson;import com.wtm.ingest.OperationalAnalytics;
import java.io.*;import java.net.URI;import java.net.http.*;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.time.Duration;import java.util.*;import java.util.concurrent.CopyOnWriteArrayList;import java.util.regex.Pattern;import java.util.zip.*;
public final class NorthStarIntelligenceService{
 public record Answer(String text,List<String>sources){}public record Status(boolean online,String detail){}private record Chunk(Path source,String text,int score){}
 private static final NorthStarIntelligenceService INSTANCE=new NorthStarIntelligenceService();private static final Pattern WORD=Pattern.compile("[^a-z0-9]+",Pattern.CASE_INSENSITIVE);private static final Set<String>STOP=Set.of("the","a","an","and","or","of","to","in","is","are","was","were","what","when","where","who","how","why","for","on","with","this","that","our","we","i","me","my","it","do","does","did","can","could","would");
 private final Path appRoot=Path.of(System.getProperty("user.home"),".northstar-operations-intelligence"),aiRoot=appRoot.resolve("ai"),knowledgeRoot=aiRoot.resolve("knowledge"),settingsFile=aiRoot.resolve("ai.properties");private final HttpClient http=HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(3)).build();private final List<Runnable>listeners=new CopyOnWriteArrayList<>();private volatile String ollamaUrl="http://127.0.0.1:11434",model="llama3.2:3b";private volatile boolean useOperationalData=true;
 private NorthStarIntelligenceService(){loadSettings();ensureDirs();}public static NorthStarIntelligenceService get(){return INSTANCE;}public String ollamaUrl(){return ollamaUrl;}public String model(){return model;}public boolean useOperationalData(){return useOperationalData;}
 public synchronized void saveSettings(String url,String m,boolean operational){ollamaUrl=normalizeUrl(url);model=m==null||m.isBlank()?"llama3.2:3b":m.trim();useOperationalData=operational;ensureDirs();Properties p=new Properties();p.setProperty("ollama.url",ollamaUrl);p.setProperty("ollama.model",model);p.setProperty("operational.data",String.valueOf(useOperationalData));try(OutputStream out=Files.newOutputStream(settingsFile,StandardOpenOption.CREATE,StandardOpenOption.TRUNCATE_EXISTING)){p.store(out,"NorthStar Intelligence local settings");}catch(IOException ignored){}}
 private void loadSettings(){try{if(!Files.exists(settingsFile))return;Properties p=new Properties();try(InputStream in=Files.newInputStream(settingsFile)){p.load(in);}ollamaUrl=normalizeUrl(p.getProperty("ollama.url",ollamaUrl));model=p.getProperty("ollama.model",model).trim();useOperationalData=Boolean.parseBoolean(p.getProperty("operational.data","true"));}catch(Exception ignored){}}
 public Status testConnection(){try{HttpRequest req=HttpRequest.newBuilder(URI.create(ollamaUrl+"/api/tags")).timeout(Duration.ofSeconds(4)).GET().build();HttpResponse<String>res=http.send(req,HttpResponse.BodyHandlers.ofString());return res.statusCode()>=200&&res.statusCode()<300?new Status(true,"Ollama online • "+model):new Status(false,"Ollama returned HTTP "+res.statusCode());}catch(Exception ex){return new Status(false,"Ollama offline • start Ollama and load "+model);}}
 public Answer ask(String question)throws Exception{String q=question==null?"":question.trim();if(q.isBlank())return new Answer("Ask a question first.",List.of());List<Chunk>context=retrieve(q);List<String>sources=new ArrayList<>(context.stream().map(c->displaySource(c.source())).distinct().limit(10).toList());String verified=useOperationalData?OperationalAnalytics.contextFor(q):"";if(!verified.isBlank())sources.add(0,"NorthStar Operational Analytics");StringBuilder evidence=new StringBuilder();if(!verified.isBlank())evidence.append("\n--- SOURCE: NorthStar Operational Analytics ---\n").append(verified).append('\n');for(Chunk c:context)evidence.append("\n--- SOURCE: ").append(displaySource(c.source())).append(" ---\n").append(c.text()).append('\n');if(context.isEmpty()&&verified.isBlank())evidence.append("\nNo matching NorthStar records or uploaded documents were found.\n");String employeeRule=AuthorizationService.allowed(Permission.AI_EMPLOYEE_METRICS)?"Employee metrics are authorized when supplied.":"Do not provide employee-specific performance, attendance, training, or personnel metrics.";String prompt="You are NorthStar Intelligence, a local operations analyst. Answer ONLY from NORTHSTAR CONTEXT. Prefer verified NorthStar Operational Analytics over raw CSV text. Never calculate a completed-day trend from a row with blank LHY or other required completion metrics; label it partial/in-progress. Preserve numbers and dates. Explain trends concisely. Distinguish correlation from causation. Cite exact source labels as [Source: ...]. "+employeeRule+"\n\nUSER QUESTION:\n"+q+"\n\nNORTHSTAR CONTEXT:\n"+evidence;Status st=testConnection();if(!st.online())return new Answer(localFallback(context,verified)+"\n\nLocal AI engine status: "+st.detail(),sources);String json="{\"model\":\""+escape(model)+"\",\"stream\":false,\"prompt\":\""+escape(prompt)+"\"}";HttpRequest req=HttpRequest.newBuilder(URI.create(ollamaUrl+"/api/generate")).timeout(Duration.ofSeconds(120)).header("Content-Type","application/json").POST(HttpRequest.BodyPublishers.ofString(json,StandardCharsets.UTF_8)).build();HttpResponse<String>res=http.send(req,HttpResponse.BodyHandlers.ofString());if(res.statusCode()<200||res.statusCode()>=300)throw new IOException("Ollama returned HTTP "+res.statusCode()+". "+res.body());String response=MiniJson.str(MiniJson.obj(MiniJson.parse(res.body())).get("response"));return new Answer(response.isBlank()?"The local model returned an empty response.":response.trim(),sources);}
 private String localFallback(List<Chunk>c,String verified){if(!verified.isBlank())return verified;if(c.isEmpty())return"I could not find matching information in NorthStar's local data or knowledge library.";return c.get(0).text();}
 public synchronized Path importDocument(Path source)throws IOException{Objects.requireNonNull(source);ensureDirs();if(!Files.isRegularFile(source))throw new IOException("Select a document file.");String ext=extension(source);if(!Set.of("txt","md","csv","json","log","docx","pdf").contains(ext))throw new IOException("Supported documents: TXT, MD, CSV, JSON, LOG, DOCX, and text-based PDF.");String safe=source.getFileName().toString().replaceAll("[^A-Za-z0-9._ -]","_");Path target=knowledgeRoot.resolve(safe);if(Files.exists(target))target=knowledgeRoot.resolve(System.currentTimeMillis()+"-"+safe);Files.copy(source,target);if(extractText(target).isBlank()){Files.deleteIfExists(target);throw new IOException("No readable document text was found.");}fire();return target;}public synchronized void removeDocument(Path f)throws IOException{if(f!=null)Files.deleteIfExists(f);fire();}public List<Path>knowledgeFiles(){ensureDirs();try(var s=Files.list(knowledgeRoot)){return s.filter(Files::isRegularFile).sorted().toList();}catch(IOException e){return List.of();}}public Path knowledgeRoot(){return knowledgeRoot;}public void addLibraryListener(Runnable r){if(r!=null)listeners.add(r);}public void removeLibraryListener(Runnable r){listeners.remove(r);}private void fire(){listeners.forEach(Runnable::run);}
 private List<Chunk>retrieve(String q){List<String>terms=terms(q);List<Path>files=new ArrayList<>(knowledgeFiles());if(useOperationalData)files.addAll(operationalFiles());List<Chunk>out=new ArrayList<>();Set<Path>seen=new HashSet<>();for(Path f:files)if(seen.add(f.toAbsolutePath().normalize()))try{String text=extractText(f);for(String ch:chunk(text,1400,180)){int sc=score(f,ch,terms);if(sc>0)out.add(new Chunk(f,ch,sc));}}catch(Exception ignored){}out.sort(Comparator.comparingInt(Chunk::score).reversed());return out.stream().limit(10).toList();}
 private List<Path>operationalFiles(){Path root=appRoot.resolve("operational-data");if(!Files.isDirectory(root))return List.of();try(var s=Files.list(root)){return s.filter(Files::isRegularFile).toList();}catch(IOException e){return List.of();}}
 private String extractText(Path f)throws IOException{if(Files.size(f)>8_000_000)throw new IOException("Document too large.");return switch(extension(f)){case"docx"->extractDocx(f);case"pdf"->extractPdf(f);default->Files.readString(f,StandardCharsets.UTF_8);};}private String extractDocx(Path f)throws IOException{try(ZipInputStream z=new ZipInputStream(Files.newInputStream(f))){for(ZipEntry e;(e=z.getNextEntry())!=null;)if("word/document.xml".equals(e.getName()))return new String(z.readAllBytes(),StandardCharsets.UTF_8).replace("</w:p>","\n").replaceAll("<[^>]+>","");}return"";}private String extractPdf(Path f){return"";}
 private static List<String>chunk(String t,int size,int overlap){List<String>o=new ArrayList<>();for(int s=0;s<t.length();){int e=Math.min(t.length(),s+size);String p=t.substring(s,e).trim();if(!p.isBlank())o.add(p);if(e>=t.length())break;s=Math.max(s+1,e-overlap);}return o;}private static int score(Path f,String text,List<String>terms){if(terms.isEmpty())return 1;String h=(f.getFileName()+" "+text).toLowerCase(Locale.ROOT);int s=0;for(String t:terms){if(h.contains(t))s+=3;if(f.getFileName().toString().toLowerCase(Locale.ROOT).contains(t))s+=8;}return s;}private static List<String>terms(String q){LinkedHashSet<String>o=new LinkedHashSet<>();for(String t:WORD.split(q.toLowerCase(Locale.ROOT)))if(t.length()>2&&!STOP.contains(t))o.add(t);return new ArrayList<>(o);}private static String extension(Path p){String n=p.getFileName().toString();int d=n.lastIndexOf('.');return d<0?"":n.substring(d+1).toLowerCase(Locale.ROOT);}private static String displaySource(Path p){return p.getFileName().toString();}private static String normalizeUrl(String u){u=u==null?"":u.trim();if(u.isBlank())u="http://127.0.0.1:11434";while(u.endsWith("/"))u=u.substring(0,u.length()-1);return u;}private void ensureDirs(){try{Files.createDirectories(knowledgeRoot);}catch(IOException ignored){}}private static String escape(String s){return s.replace("\\","\\\\").replace("\"","\\\"").replace("\n","\\n").replace("\r","\\r");}
}
