package com.wtm.ai;

import com.wtm.ingest.OperationalContextEngine;import com.wtm.security.AuthorizationService;import com.wtm.security.Permission;import com.wtm.util.MiniJson;
import java.io.*;import java.net.URI;import java.net.http.*;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.time.*;import java.util.*;import java.util.concurrent.CopyOnWriteArrayList;import java.util.regex.Pattern;import java.util.zip.*;

/** Local NorthStar Intelligence service with deterministic operational routing before LLM synthesis. */
public final class NorthStarIntelligenceService{
 public record Answer(String text,List<String>sources){}public record Status(boolean online,String detail){}private record Chunk(Path source,String text,int score){}
 private static final NorthStarIntelligenceService INSTANCE=new NorthStarIntelligenceService();private static final Pattern WORD=Pattern.compile("[^a-z0-9]+",Pattern.CASE_INSENSITIVE);private static final Set<String>STOP=Set.of("the","a","an","and","or","of","to","in","is","are","was","were","what","when","where","who","how","why","for","on","with","this","that","our","we","i","me","my","it","do","does","did","can","could","would");
 private final Path appRoot=Path.of(System.getProperty("user.home"),".northstar-operations-intelligence"),aiRoot=appRoot.resolve("ai"),knowledgeRoot=aiRoot.resolve("knowledge"),settingsFile=aiRoot.resolve("ai.properties");private final HttpClient http=HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(4)).build();private final List<Runnable>listeners=new CopyOnWriteArrayList<>();private volatile String ollamaUrl="http://127.0.0.1:11434",model="llama3.2:3b";private volatile boolean useOperationalData=true;
 private NorthStarIntelligenceService(){loadSettings();ensureDirs();}public static NorthStarIntelligenceService get(){return INSTANCE;}public String ollamaUrl(){return ollamaUrl;}public String model(){return model;}public boolean useOperationalData(){return useOperationalData;}
 public synchronized void saveSettings(String url,String m,boolean operational){ollamaUrl=normalizeUrl(url);model=m==null||m.isBlank()?"llama3.2:3b":m.trim();useOperationalData=operational;ensureDirs();Properties p=new Properties();p.setProperty("ollama.url",ollamaUrl);p.setProperty("ollama.model",model);p.setProperty("operational.data",String.valueOf(useOperationalData));try(OutputStream out=Files.newOutputStream(settingsFile,StandardOpenOption.CREATE,StandardOpenOption.TRUNCATE_EXISTING)){p.store(out,"NorthStar Intelligence local settings");}catch(IOException ignored){}}
 private void loadSettings(){try{if(!Files.exists(settingsFile))return;Properties p=new Properties();try(InputStream in=Files.newInputStream(settingsFile)){p.load(in);}ollamaUrl=normalizeUrl(p.getProperty("ollama.url",ollamaUrl));model=p.getProperty("ollama.model",model).trim();useOperationalData=Boolean.parseBoolean(p.getProperty("operational.data","true"));}catch(Exception ignored){}}
 public Status testConnection(){try{HttpRequest req=HttpRequest.newBuilder(URI.create(ollamaUrl+"/api/tags")).timeout(Duration.ofSeconds(5)).GET().build();HttpResponse<String>res=http.send(req,HttpResponse.BodyHandlers.ofString());if(res.statusCode()<200||res.statusCode()>=300)return new Status(false,"Ollama returned HTTP "+res.statusCode());Map<String,Object>root=MiniJson.obj(MiniJson.parse(res.body()));boolean found=false;for(Object o:safeArr(root.get("models"))){Map<String,Object>x=safeObj(o);String n=MiniJson.str(x.get("name"));if(n.equals(model)||n.startsWith(model+":"))found=true;}return found?new Status(true,"Ollama ready • "+model):new Status(false,"Ollama online • configured model not found: "+model);}catch(Exception ex){return new Status(false,"Ollama offline • start Ollama and load "+model);}}

 public Answer ask(String question)throws Exception{
  String q=question==null?"":question.trim();if(q.isBlank())return new Answer("Ask a question first.",List.of());
  OperationalContextEngine.Analysis op=useOperationalData?OperationalContextEngine.analyze(q):OperationalContextEngine.analyze("");
  if(op.view()==OperationalContextEngine.View.UNSUPPORTED)return new Answer("NorthStar only makes operational claims that can be supported by imported, connected, or uploaded evidence. I can tell you what data would be needed for an unsupported question, but I will not invent an operational fact that is not present in NorthStar's evidence.",List.of());
  List<Chunk>docs=retrieveKnowledge(q);List<String>sources=new ArrayList<>();sources.addAll(op.sources());for(Chunk c:docs){String s=displaySource(c.source());if(!sources.contains(s))sources.add(s);}StringBuilder evidence=new StringBuilder();if(op.operationalIntent())evidence.append("\n--- VERIFIED OPERATIONAL CONTEXT ---\n").append(op.context()).append('\n');for(Chunk c:docs)evidence.append("\n--- DOCUMENT SOURCE: ").append(displaySource(c.source())).append(" ---\n").append(c.text()).append('\n');
  if(!op.operationalIntent()&&docs.isEmpty())return new Answer("NorthStar could not find evidence relevant to that question in its connected operational datasets or knowledge library. I won't substitute an unrelated dataset. Import or connect the required information, or ask what data NorthStar currently has available.",List.of());
  if(op.operationalIntent()&&op.sources().isEmpty()&&docs.isEmpty())return new Answer(op.context().contains("Required operational feed not loaded")?op.context().substring(op.context().indexOf("Required operational feed")):"NorthStar does not currently have the required operational feed for that question. I won't use an unrelated source as a substitute.",List.of());
  String employeeRule=AuthorizationService.allowed(Permission.AI_EMPLOYEE_METRICS)?"Employee-level metrics may be used when they are explicitly present in VERIFIED OPERATIONAL CONTEXT.":"Do not identify or rank employees by performance. Employee-level AI metrics permission is not granted.";
  String prompt="You are NorthStar Intelligence, an evidence-grounded operations analyst.\nCURRENT LOCAL DATE: "+LocalDate.now()+". Never claim another current date.\nAnswer ONLY from the supplied NORTHSTAR EVIDENCE. Never substitute an unrelated dataset.\nVERIFIED OPERATIONAL CONTEXT has priority over document snippets and raw text. The Java analytics layer already performed calculations; preserve those values rather than recalculating from guesses.\nFor broad operations questions, synthesize across every operational section supplied. Identify positives, risks, freshness limitations, and what deserves attention.\nFor today/current questions, explicitly distinguish today's data from the latest imported snapshot or latest completed day.\nFor why/cause questions, separate observed facts from possible hypotheses and never state causation unless evidence proves it.\nFor unsupported information, state what is missing instead of inventing it.\nDo not tell the user to upload information if the evidence packet already contains the relevant domain.\nCite factual claims with [Source: filename] when source filenames are supplied.\n"+employeeRule+"\n\nUSER QUESTION:\n"+q+"\n\nNORTHSTAR EVIDENCE:\n"+evidence;
  Status st=testConnection();if(!st.online())return new Answer(localFallback(op,docs)+"\n\nLocal AI engine status: "+st.detail(),sources);
  String body="{\"model\":\""+escape(model)+"\",\"stream\":false,\"prompt\":\""+escape(prompt)+"\",\"options\":{\"temperature\":0.2}}";HttpRequest req=HttpRequest.newBuilder(URI.create(ollamaUrl+"/api/generate")).timeout(Duration.ofSeconds(180)).header("Content-Type","application/json").POST(HttpRequest.BodyPublishers.ofString(body,StandardCharsets.UTF_8)).build();HttpResponse<String>res=http.send(req,HttpResponse.BodyHandlers.ofString());if(res.statusCode()<200||res.statusCode()>=300)throw new IOException("Ollama returned HTTP "+res.statusCode()+". "+res.body());String response=MiniJson.str(MiniJson.obj(MiniJson.parse(res.body())).get("response"));return new Answer(response.isBlank()?localFallback(op,docs):response.trim(),sources);
 }
 private String localFallback(OperationalContextEngine.Analysis op,List<Chunk>docs){if(op.operationalIntent()&&!op.context().isBlank())return op.context();if(!docs.isEmpty())return docs.get(0).text();return "No supported NorthStar evidence was found for that question.";}

 public synchronized Path importDocument(Path source)throws IOException{Objects.requireNonNull(source);ensureDirs();if(!Files.isRegularFile(source))throw new IOException("Select a document file.");String ext=extension(source);if(!Set.of("txt","md","csv","json","log","docx","pdf").contains(ext))throw new IOException("Supported documents: TXT, MD, CSV, JSON, LOG, DOCX, and text-based PDF.");String safe=source.getFileName().toString().replaceAll("[^A-Za-z0-9._ -]","_");Path target=knowledgeRoot.resolve(safe);if(Files.exists(target))target=knowledgeRoot.resolve(System.currentTimeMillis()+"-"+safe);Files.copy(source,target);if(extractText(target).isBlank()){Files.deleteIfExists(target);throw new IOException("No readable document text was found.");}fire();return target;}public synchronized void removeDocument(Path f)throws IOException{if(f!=null)Files.deleteIfExists(f);fire();}public List<Path>knowledgeFiles(){ensureDirs();try(var s=Files.list(knowledgeRoot)){return s.filter(Files::isRegularFile).sorted().toList();}catch(IOException e){return List.of();}}public Path knowledgeRoot(){return knowledgeRoot;}public void addLibraryListener(Runnable r){if(r!=null)listeners.add(r);}public void removeLibraryListener(Runnable r){listeners.remove(r);}private void fire(){listeners.forEach(Runnable::run);}
 private List<Chunk>retrieveKnowledge(String q){List<String>terms=terms(q);List<Chunk>out=new ArrayList<>();for(Path f:knowledgeFiles())try{String text=extractText(f);for(String ch:chunk(text,1500,180)){int sc=score(f,ch,terms);if(sc>0)out.add(new Chunk(f,ch,sc));}}catch(Exception ignored){}out.sort(Comparator.comparingInt(Chunk::score).reversed());return out.stream().limit(8).toList();}
 private String extractText(Path f)throws IOException{if(Files.size(f)>8_000_000)throw new IOException("Document too large.");return switch(extension(f)){case"docx"->extractDocx(f);case"pdf"->extractPdf(f);default->Files.readString(f,StandardCharsets.UTF_8);};}private String extractDocx(Path f)throws IOException{try(ZipInputStream z=new ZipInputStream(Files.newInputStream(f))){for(ZipEntry e;(e=z.getNextEntry())!=null;)if("word/document.xml".equals(e.getName()))return new String(z.readAllBytes(),StandardCharsets.UTF_8).replace("</w:p>","\n").replaceAll("<[^>]+>","");}return"";}private String extractPdf(Path f){return"";}
 private static List<String>chunk(String t,int size,int overlap){List<String>o=new ArrayList<>();for(int s=0;s<t.length();){int e=Math.min(t.length(),s+size);String p=t.substring(s,e).trim();if(!p.isBlank())o.add(p);if(e>=t.length())break;s=Math.max(s+1,e-overlap);}return o;}private static int score(Path f,String text,List<String>terms){if(terms.isEmpty())return 1;String h=(f.getFileName()+" "+text).toLowerCase(Locale.ROOT);int s=0;for(String t:terms){int at=0,count=0;while((at=h.indexOf(t,at))>=0&&count<8){s+=3;count++;at+=t.length();}if(f.getFileName().toString().toLowerCase(Locale.ROOT).contains(t))s+=8;}return s;}private static List<String>terms(String q){LinkedHashSet<String>o=new LinkedHashSet<>();for(String t:WORD.split(q.toLowerCase(Locale.ROOT)))if(t.length()>2&&!STOP.contains(t))o.add(t);return new ArrayList<>(o);}private static String extension(Path p){String n=p.getFileName().toString();int d=n.lastIndexOf('.');return d<0?"":n.substring(d+1).toLowerCase(Locale.ROOT);}private static String displaySource(Path p){return p.getFileName().toString();}private static String normalizeUrl(String u){u=u==null?"":u.trim();if(u.isBlank())u="http://127.0.0.1:11434";while(u.endsWith("/"))u=u.substring(0,u.length()-1);return u;}private void ensureDirs(){try{Files.createDirectories(knowledgeRoot);}catch(IOException ignored){}}private static String escape(String s){return s.replace("\\","\\\\").replace("\"","\\\"").replace("\n","\\n").replace("\r","\\r").replace("\t","\\t");}private static List<Object>safeArr(Object x){return x instanceof List<?>?MiniJson.arr(x):List.of();}private static Map<String,Object>safeObj(Object x){return x instanceof Map<?,?>?MiniJson.obj(x):Map.of();}
}
