package com.wtm.firstparty;
import java.nio.file.*;import java.nio.charset.StandardCharsets;import java.io.*;import java.util.*;
public final class NetworkLocationStore {
 private static final NetworkLocationStore I=new NetworkLocationStore(); private final Path file=Path.of(System.getProperty("user.home"),".northstar-operations-intelligence","tracking","logistics-network.csv"); private final List<NetworkLocation> rows=new ArrayList<>(); private boolean loaded;
 public static NetworkLocationStore get(){return I;}
 public synchronized List<NetworkLocation> all(){load();return new ArrayList<>(rows);}
 public synchronized NetworkLocation find(String id){load();return rows.stream().filter(x->Objects.equals(x.id(),id)).findFirst().orElse(null);}
 public synchronized void upsert(NetworkLocation n){load();int ix=-1;for(int i=0;i<rows.size();i++)if(rows.get(i).id().equals(n.id())){ix=i;break;}if(ix>=0)rows.set(ix,n);else rows.add(n);save();}
 public synchronized void delete(String id){load();rows.removeIf(x->x.id().equals(id));save();}
 public synchronized int importCsv(Path p)throws IOException{load();List<String> ls=Files.readAllLines(p,StandardCharsets.UTF_8);if(ls.isEmpty())return 0;List<String> h=CsvUtil.parse(ls.get(0));Map<String,Integer> m=new HashMap<>();for(int i=0;i<h.size();i++)m.put(h.get(i).trim().toLowerCase(Locale.ROOT),i);int n=0;for(int r=1;r<ls.size();r++){if(ls.get(r).isBlank())continue;List<String> c=CsvUtil.parse(ls.get(r));String name=v(c,m,"name","dealername","facility");if(name.isBlank())continue;String cat=v(c,m,"category","type");if(cat.isBlank())cat=m.containsKey("dealerid")||m.containsKey("dealer")?"Dealer":"Other";String ext=v(c,m,"externalid","dealerid","customerbk","dealernumber","dealer");String addr=v(c,m,"address","streetaddress");String city=v(c,m,"city");String state=v(c,m,"state");String zip=v(c,m,"zip","zipcode","postalcode");if(addr.isBlank()&&!city.isBlank())addr=(city+(state.isBlank()?"":", "+state)+(zip.isBlank()?"":" "+zip)).trim();String id=v(c,m,"id");if(id.isBlank())id=UUID.randomUUID().toString();double lat=CsvUtil.d(v(c,m,"latitude","lat"),Double.NaN),lon=CsvUtil.d(v(c,m,"longitude","lon","lng"),Double.NaN);int gf=CsvUtil.i(v(c,m,"geofencemeters","geofence"),cat.equalsIgnoreCase("Dealer")?250:500);boolean active=CsvUtil.b(v(c,m,"active"),true);upsert(new NetworkLocation(id,name,cat,addr,ext,lat,lon,gf,v(c,m,"notes"),active));n++;}return n;}
 public synchronized void exportTemplate(Path p)throws IOException{Files.writeString(p,"Name,Category,Address,DealerID,Latitude,Longitude,GeofenceMeters,Notes,Active\nExample Dealer,Dealer,123 Main St Birmingham AL 35203,12345,,,250,,true\n",StandardCharsets.UTF_8);}
 private static String v(List<String> c,Map<String,Integer> m,String...ks){for(String k:ks){Integer i=m.get(k.toLowerCase(Locale.ROOT));if(i!=null&&i<c.size())return CsvUtil.clean(c.get(i));}return "";}
 private void load(){if(loaded)return;loaded=true;if(!Files.exists(file))return;try{List<String> ls=Files.readAllLines(file,StandardCharsets.UTF_8);for(int r=1;r<ls.size();r++){List<String> c=CsvUtil.parse(ls.get(r));if(c.size()<10)continue;rows.add(new NetworkLocation(c.get(0),c.get(1),c.get(2),c.get(3),c.get(4),CsvUtil.d(c.get(5),Double.NaN),CsvUtil.d(c.get(6),Double.NaN),CsvUtil.i(c.get(7),500),c.get(8),CsvUtil.b(c.get(9),true)));}}catch(Exception ignored){}}
 private void save(){try{Files.createDirectories(file.getParent());StringBuilder b=new StringBuilder("Id,Name,Category,Address,ExternalId,Latitude,Longitude,GeofenceMeters,Notes,Active\n");for(NetworkLocation n:rows)b.append(String.join(",",CsvUtil.q(n.id()),CsvUtil.q(n.name()),CsvUtil.q(n.category()),CsvUtil.q(n.address()),CsvUtil.q(n.externalId()),CsvUtil.q(n.latitude()),CsvUtil.q(n.longitude()),CsvUtil.q(n.geofenceMeters()),CsvUtil.q(n.notes()),CsvUtil.q(n.active()))).append('\n');Files.writeString(file,b.toString(),StandardCharsets.UTF_8);}catch(Exception ignored){}}
}
