package com.wtm.firstparty;
import java.nio.file.*;import java.nio.charset.StandardCharsets;import java.io.*;import java.util.*;
public final class NetworkLocationStore{
 private static final NetworkLocationStore I=new NetworkLocationStore();private final Path file=Path.of(System.getProperty("user.home"),".northstar-operations-intelligence","tracking","logistics-network.csv");private final List<NetworkLocation> rows=new ArrayList<>();private boolean loaded;
 public static NetworkLocationStore get(){return I;}public synchronized List<NetworkLocation> all(){load();return new ArrayList<>(rows);}public synchronized NetworkLocation find(String id){load();return rows.stream().filter(x->Objects.equals(x.id(),id)).findFirst().orElse(null);}
 public synchronized void upsert(NetworkLocation n){load();int ix=index(n.id());if(ix>=0)rows.set(ix,n);else rows.add(n);save();}public synchronized void delete(String id){load();rows.removeIf(x->x.id().equals(id));save();}
 public synchronized int importCsv(Path p)throws IOException{load();List<String>ls=Files.readAllLines(p,StandardCharsets.UTF_8);if(ls.isEmpty())return 0;List<String>h=CsvUtil.parse(ls.get(0));Map<String,Integer>m=header(h);if(isDview(m))return importDview(ls,m);return importGeneric(ls,m);}
 public synchronized void exportTemplate(Path p)throws IOException{Files.writeString(p,"ID,TYPE,ENTITYID,LINE1,LINE2,LINE3,CITY,REGION,COUNTRYBK,POSTALCODE,ARCHIVESTATUS,LASTUPDATEDT\nYEXAMPLE1,1,055106,MERCEDES-BENZ OF EXAMPLE,123 MAIN STREET,,BIRMINGHAM,AL,US,35203,2,2026-08-24 12:00:00.000\nYEXAMPLE2,2,US08,Jacksonville PDC,13470 International Parkway,,JACKSONVILLE,FL,US,32218,2,2026-08-24 12:00:00.000\n",StandardCharsets.UTF_8);}
 private int importDview(List<String>ls,Map<String,Integer>m){record R(String addressId,String type,String entity,String name,String address,String archive,String updated,String category){}Map<String,R> newest=new LinkedHashMap<>();for(int r=1;r<ls.size();r++){if(ls.get(r).isBlank())continue;List<String>c=CsvUtil.parse(ls.get(r));String aid=v(c,m,"id"),type=v(c,m,"type"),entity=v(c,m,"entityid"),name=v(c,m,"line1"),line2=v(c,m,"line2"),line3=v(c,m,"line3"),city=v(c,m,"city"),region=v(c,m,"region"),country=v(c,m,"countrybk"),postal=v(c,m,"postalcode"),archive=v(c,m,"archivestatus"),updated=v(c,m,"lastupdatedt");if(entity.isBlank()||name.isBlank())continue;String category=category(type,entity,name+" "+line2);if(category==null)continue;String address=address(line2,line3,city,region,postal,country);R x=new R(aid,type,entity,name,address,archive,updated,category),old=newest.get(category+"|"+entity);if(old==null||updated.compareTo(old.updated())>0)newest.put(category+"|"+entity,x);}int changed=0;for(R x:newest.values()){NetworkLocation old=findEntity(x.entity(),x.category());String id=old==null?"DVIEW-"+safe(x.category())+"-"+x.entity():old.id();boolean same=old!=null&&norm(old.address()).equals(norm(x.address()));double lat=same?old.latitude():Double.NaN,lon=same?old.longitude():Double.NaN;int gf=old!=null?old.geofenceMeters():(x.category().equals("Dealer")?250:500);String notes="Source=DVIEW Address; DVIEW_ADDRESS_ID="+x.addressId()+"; DVIEW_TYPE="+x.type()+"; ARCHIVESTATUS="+x.archive()+"; LASTUPDATEDT="+x.updated();NetworkLocation n=new NetworkLocation(id,x.name(),x.category(),x.address(),x.entity(),lat,lon,gf,notes,true);if(old==null||!equivalent(old,n)){if(old==null)rows.add(n);else rows.set(index(old.id()),n);changed++;}}if(changed>0)save();return changed;}
 private int importGeneric(List<String>ls,Map<String,Integer>m){int n=0;for(int r=1;r<ls.size();r++){if(ls.get(r).isBlank())continue;List<String>c=CsvUtil.parse(ls.get(r));String name=v(c,m,"name","dealername","facility");if(name.isBlank())continue;String cat=v(c,m,"category","type");if(cat.isBlank())cat=m.containsKey("dealerid")||m.containsKey("dealer")?"Dealer":"Other / Temporary Destination";String ext=v(c,m,"externalid","dealerid","customerbk","dealernumber","dealer"),addr=v(c,m,"address","streetaddress"),city=v(c,m,"city"),state=v(c,m,"state"),zip=v(c,m,"zip","zipcode","postalcode");if(addr.isBlank()&&!city.isBlank())addr=(city+(state.isBlank()?"":", "+state)+(zip.isBlank()?"":" "+zip)).trim();NetworkLocation old=findEntity(ext,cat);String id=v(c,m,"id");if(id.isBlank())id=old==null?UUID.randomUUID().toString():old.id();double lat=CsvUtil.d(v(c,m,"latitude","lat"),old==null?Double.NaN:old.latitude()),lon=CsvUtil.d(v(c,m,"longitude","lon","lng"),old==null?Double.NaN:old.longitude());int gf=CsvUtil.i(v(c,m,"geofencemeters","geofence"),cat.equalsIgnoreCase("Dealer")?250:500);boolean active=CsvUtil.b(v(c,m,"active"),true);NetworkLocation x=new NetworkLocation(id,name,cat,addr,ext,lat,lon,gf,v(c,m,"notes"),active);if(old==null){rows.add(x);n++;}else if(!equivalent(old,x)){rows.set(index(old.id()),x);n++;}}if(n>0)save();return n;}
 private NetworkLocation findEntity(String ext,String cat){if(ext==null||ext.isBlank())return null;for(NetworkLocation n:rows)if(ext.equalsIgnoreCase(n.externalId())&&cat.equalsIgnoreCase(n.category()))return n;return null;}private int index(String id){for(int i=0;i<rows.size();i++)if(rows.get(i).id().equals(id))return i;return-1;}
 private static String category(String type,String entity,String text){String u=(text==null?"":text).toUpperCase(Locale.ROOT),e=entity.toUpperCase(Locale.ROOT);if("6".equals(type)||e.matches("US\\d{2}")||u.matches(".*\\bPDC\\b.*")||u.contains("PARTS DISTRIBUTION")||u.contains("LOGISTICS")||u.contains("WAREHOUSE")||u.contains(" VPC")||u.contains("R.M.")||u.contains("DISTRIBUTION CENTER")||u.contains("MARSHALLING"))return "Logistics Center";try{if(("1".equals(type)||"2".equals(type))&&e.matches("\\d{6}")&&Integer.parseInt(e)>=1000)return "Dealer";}catch(Exception ignored){}return null;}
 private static boolean equivalent(NetworkLocation a,NetworkLocation b){return Objects.equals(a.name(),b.name())&&Objects.equals(a.category(),b.category())&&Objects.equals(a.address(),b.address())&&Objects.equals(a.externalId(),b.externalId())&&Double.compare(a.latitude(),b.latitude())==0&&Double.compare(a.longitude(),b.longitude())==0&&a.geofenceMeters()==b.geofenceMeters()&&Objects.equals(a.notes(),b.notes())&&a.active()==b.active();}
 private static String address(String l2,String l3,String city,String region,String postal,String country){List<String>a=new ArrayList<>();if(!l2.isBlank())a.add(l2);if(!l3.isBlank())a.add(l3);String tail=(city+(region.isBlank()?"":" "+region)+(postal.isBlank()?"":" "+postal)+(country.isBlank()?"":" "+country)).trim();if(!tail.isBlank())a.add(tail);return String.join(", ",a);}private static String norm(String s){return s==null?"":s.toUpperCase(Locale.ROOT).replaceAll("[^A-Z0-9]","");}private static String safe(String s){return s.toUpperCase(Locale.ROOT).replaceAll("[^A-Z0-9]+","-");}private static Map<String,Integer>header(List<String>h){Map<String,Integer>m=new HashMap<>();for(int i=0;i<h.size();i++)m.put(h.get(i).trim().toLowerCase(Locale.ROOT),i);return m;}private static boolean isDview(Map<String,Integer>m){return m.keySet().containsAll(Set.of("id","type","entityid","line1","line2","city","countrybk","postalcode","archivestatus","lastupdatedt"));}private static String v(List<String>c,Map<String,Integer>m,String...ks){for(String k:ks){Integer i=m.get(k.toLowerCase(Locale.ROOT));if(i!=null&&i<c.size())return CsvUtil.clean(c.get(i));}return"";}
 private void load(){if(loaded)return;loaded=true;if(!Files.exists(file))return;try{List<String>ls=Files.readAllLines(file,StandardCharsets.UTF_8);for(int r=1;r<ls.size();r++){List<String>c=CsvUtil.parse(ls.get(r));if(c.size()<10)continue;rows.add(new NetworkLocation(c.get(0),c.get(1),c.get(2),c.get(3),c.get(4),CsvUtil.d(c.get(5),Double.NaN),CsvUtil.d(c.get(6),Double.NaN),CsvUtil.i(c.get(7),500),c.get(8),CsvUtil.b(c.get(9),true)));}}catch(Exception ignored){}}
 private void save(){try{Files.createDirectories(file.getParent());StringBuilder b=new StringBuilder("Id,Name,Category,Address,ExternalId,Latitude,Longitude,GeofenceMeters,Notes,Active\n");for(NetworkLocation n:rows)b.append(String.join(",",CsvUtil.q(n.id()),CsvUtil.q(n.name()),CsvUtil.q(n.category()),CsvUtil.q(n.address()),CsvUtil.q(n.externalId()),CsvUtil.q(n.latitude()),CsvUtil.q(n.longitude()),CsvUtil.q(n.geofenceMeters()),CsvUtil.q(n.notes()),CsvUtil.q(n.active()))).append('\n');Files.writeString(file,b.toString(),StandardCharsets.UTF_8);}catch(Exception ignored){}}
}
