package com.wtm.firstparty;
import java.nio.file.*;import java.nio.charset.StandardCharsets;import java.util.*;
public final class TrackerRegistryStore {
 private static final TrackerRegistryStore I=new TrackerRegistryStore(); private final Path file=Path.of(System.getProperty("user.home"),".northstar-operations-intelligence","tracking","tracker-devices.csv");private final List<TrackerDevice> rows=new ArrayList<>();private boolean loaded;
 public static TrackerRegistryStore get(){return I;} public synchronized List<TrackerDevice> all(){load();return new ArrayList<>(rows);} public synchronized TrackerDevice find(String id){load();return rows.stream().filter(x->x.id().equals(id)).findFirst().orElse(null);}
 public synchronized void upsert(TrackerDevice d){load();int ix=-1;for(int i=0;i<rows.size();i++)if(rows.get(i).id().equals(d.id())){ix=i;break;}if(ix>=0)rows.set(ix,d);else rows.add(d);save();}
 public synchronized void delete(String id){load();rows.removeIf(x->x.id().equals(id));save();}
 public synchronized void updateTelemetry(TrackerTelemetry t){TrackerDevice d=find(t.deviceId());if(d==null)d=new TrackerDevice(t.deviceId(),"","",t.deviceId(),"ONLINE",t.batteryPct(),t.signal(),"",t.latitude(),t.longitude(),t.timestamp(),"");else d=new TrackerDevice(d.id(),d.hardwareId(),d.imei(),d.label(),"ONLINE",t.batteryPct(),t.signal(),d.firmware(),t.latitude(),t.longitude(),t.timestamp(),d.notes());upsert(d);}
 private void load(){if(loaded)return;loaded=true;if(!Files.exists(file))return;try{for(String l:Files.readAllLines(file,StandardCharsets.UTF_8).stream().skip(1).toList()){List<String> c=CsvUtil.parse(l);if(c.size()<12)continue;rows.add(new TrackerDevice(c.get(0),c.get(1),c.get(2),c.get(3),c.get(4),CsvUtil.d(c.get(5),0),CsvUtil.i(c.get(6),0),c.get(7),CsvUtil.d(c.get(8),Double.NaN),CsvUtil.d(c.get(9),Double.NaN),c.get(10),c.get(11)));}}catch(Exception ignored){}}
 private void save(){try{Files.createDirectories(file.getParent());StringBuilder b=new StringBuilder("Id,HardwareId,IMEI,Label,Status,BatteryPct,Signal,Firmware,Latitude,Longitude,LastSeen,Notes\n");for(TrackerDevice d:rows)b.append(String.join(",",CsvUtil.q(d.id()),CsvUtil.q(d.hardwareId()),CsvUtil.q(d.imei()),CsvUtil.q(d.label()),CsvUtil.q(d.status()),CsvUtil.q(d.batteryPct()),CsvUtil.q(d.signal()),CsvUtil.q(d.firmware()),CsvUtil.q(d.latitude()),CsvUtil.q(d.longitude()),CsvUtil.q(d.lastSeen()),CsvUtil.q(d.notes()))).append('\n');Files.writeString(file,b.toString(),StandardCharsets.UTF_8);}catch(Exception ignored){}}
}
