package com.wtm.firstparty;
import com.wtm.config.ConfigService;
import java.nio.file.*;import java.nio.charset.StandardCharsets;import java.io.*;import java.util.*;
public final class TrackerTelemetryStore {
 private static final TrackerTelemetryStore I=new TrackerTelemetryStore();private final Path file=ConfigService.appDataDir().resolve("tracking").resolve("tracker-telemetry.csv");
 public static TrackerTelemetryStore get(){return I;}
 public synchronized void append(TrackerTelemetry t){try{Files.createDirectories(file.getParent());boolean n=!Files.exists(file);String s=(n?"DeviceId,Timestamp,Latitude,Longitude,SpeedMph,BatteryPct,Signal,Source\n":"")+String.join(",",CsvUtil.q(t.deviceId()),CsvUtil.q(t.timestamp()),CsvUtil.q(t.latitude()),CsvUtil.q(t.longitude()),CsvUtil.q(t.speedMph()),CsvUtil.q(t.batteryPct()),CsvUtil.q(t.signal()),CsvUtil.q(t.source()))+"\n";Files.writeString(file,s,StandardCharsets.UTF_8,StandardOpenOption.CREATE,StandardOpenOption.APPEND);TrackerRegistryStore.get().updateTelemetry(t);TrackerTripStore.get().process(t);}catch(Exception ignored){}}
 public synchronized int importCsv(Path p)throws IOException{List<String> ls=Files.readAllLines(p,StandardCharsets.UTF_8);if(ls.size()<2)return 0;List<String> h=CsvUtil.parse(ls.get(0));Map<String,Integer> m=new HashMap<>();for(int i=0;i<h.size();i++)m.put(h.get(i).trim().toLowerCase(),i);int n=0;for(String l:ls.subList(1,ls.size())){if(l.isBlank())continue;List<String> c=CsvUtil.parse(l);String dev=v(c,m,"deviceid","trackerid","imei");if(dev.isBlank())continue;TrackerTelemetry t=new TrackerTelemetry(dev,v(c,m,"timestamp","time"),CsvUtil.d(v(c,m,"latitude","lat"),Double.NaN),CsvUtil.d(v(c,m,"longitude","lon","lng"),Double.NaN),CsvUtil.d(v(c,m,"speedmph","speed"),0),CsvUtil.d(v(c,m,"batterypct","battery"),0),CsvUtil.i(v(c,m,"signal","rssi"),0),"CSV");if(Double.isFinite(t.latitude())&&Double.isFinite(t.longitude())){append(t);n++;}}return n;}
 private static String v(List<String> c,Map<String,Integer> m,String...ks){for(String k:ks){Integer i=m.get(k);if(i!=null&&i<c.size())return c.get(i).trim();}return "";}
}
