package com.wtm.firstparty;
import com.wtm.config.ConfigService;
import com.wtm.truck.*;import java.nio.file.*;import java.nio.charset.StandardCharsets;import java.time.*;import java.util.*;
public final class TrackerTripStore {
 private static final TrackerTripStore I=new TrackerTripStore();private final Path file=ConfigService.appDataDir().resolve("tracking").resolve("tracker-trips.csv");private final List<TrackerTrip> rows=new ArrayList<>();private boolean loaded;
 public static TrackerTripStore get(){return I;} public synchronized List<TrackerTrip> all(){load();return new ArrayList<>(rows);} public synchronized TrackerTrip activeForDevice(String d){load();for(int i=rows.size()-1;i>=0;i--){TrackerTrip t=rows.get(i);if(t.deviceId().equals(d)&&!t.state().equals("RETURNED")&&!t.state().equals("CANCELLED"))return t;}return null;}
 public synchronized void upsert(TrackerTrip t){load();int ix=-1;for(int i=0;i<rows.size();i++)if(rows.get(i).id().equals(t.id())){ix=i;break;}if(ix>=0)rows.set(ix,t);else rows.add(t);save();syncShipment(t,null);}
 public synchronized void process(TrackerTelemetry tel){TrackerTrip t=activeForDevice(tel.deviceId());if(t==null)return;NetworkLocation dest=NetworkLocationStore.get().find(t.destinationId());NetworkLocation home=home();String state=t.state();if(dest!=null&&dest.hasCoordinates()){double dd=dist(tel.latitude(),tel.longitude(),dest.latitude(),dest.longitude());boolean inDest=dd<=Math.max(100,dest.geofenceMeters());if((state.equals("ASSIGNED")||state.equals("OUTBOUND_IN_TRANSIT"))&&inDest)state="ARRIVED_DESTINATION";else if(state.equals("ARRIVED_DESTINATION")&&!inDest)state="DELIVERED_RETURNING";}if(home!=null&&home.hasCoordinates()){double dh=dist(tel.latitude(),tel.longitude(),home.latitude(),home.longitude());boolean inHome=dh<=Math.max(150,home.geofenceMeters());if(state.equals("ASSIGNED")&&!inHome)state="OUTBOUND_IN_TRANSIT";else if(state.equals("DELIVERED_RETURNING")&&inHome)state="RETURNED";}TrackerTrip n=new TrackerTrip(t.id(),t.deviceId(),t.trailerId(),t.shipmentId(),t.destinationId(),state,t.assignedAt(),t.scheduledArrival(),t.estimatedArrival(),t.delayMinutes(),tel.timestamp(),t.notes());replace(n);syncShipment(n,tel);}
 private void replace(TrackerTrip t){int ix=-1;for(int i=0;i<rows.size();i++)if(rows.get(i).id().equals(t.id())){ix=i;break;}if(ix>=0)rows.set(ix,t);else rows.add(t);save();}
 private void syncShipment(TrackerTrip t,TrackerTelemetry tel){try{TruckTrackingStore s=TruckTrackingStore.get();TruckShipment sh=t.shipmentId()==null||t.shipmentId().isBlank()?null:s.find(t.shipmentId());if(sh==null){sh=new TruckShipment();sh.id=t.shipmentId()==null||t.shipmentId().isBlank()?"TRACKER-"+t.id():t.shipmentId();sh.carrier=TruckCarrier.OTHER;sh.trailerNumber=t.trailerId();sh.trackingNumber=t.deviceId();sh.sourceSystem="NorthStar Tracker";sh.shippedDate=LocalDate.now();}NetworkLocation d=NetworkLocationStore.get().find(t.destinationId());sh.destination=d==null?"":d.name();sh.routeName=d==null?"":d.name();sh.providerStatus=t.state();sh.status=switch(t.state()){case "ASSIGNED"->TruckStatus.PLANNED;case "OUTBOUND_IN_TRANSIT"->TruckStatus.IN_TRANSIT;case "ARRIVED_DESTINATION"->TruckStatus.ARRIVED;case "DELIVERED_RETURNING","RETURNED"->TruckStatus.DELIVERED;default->TruckStatus.PLANNED;};if(tel!=null){sh.latitude=tel.latitude();sh.longitude=tel.longitude();sh.currentLocation=t.state().equals("DELIVERED_RETURNING")?"Returning to Tuscaloosa LC":(d==null?t.state():t.state()+" • "+d.name());sh.lastUpdated=LocalDateTime.now();}if(t.state().equals("DELIVERED_RETURNING")&&sh.deliveredAt==null)sh.deliveredAt=LocalDateTime.now();s.upsert(sh);}catch(Exception ignored){}}
 private NetworkLocation home(){for(NetworkLocation n:NetworkLocationStore.get().all())if(n.category().equalsIgnoreCase("Home / Origin")||n.name().toLowerCase().contains("tuscaloosa"))return n;return null;}
 private static double dist(double a,double b,double c,double d){double R=6371000,pa=Math.toRadians(a),pc=Math.toRadians(c),dp=Math.toRadians(c-a),dl=Math.toRadians(d-b);double x=Math.sin(dp/2)*Math.sin(dp/2)+Math.cos(pa)*Math.cos(pc)*Math.sin(dl/2)*Math.sin(dl/2);return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));}
 private void load(){if(loaded)return;loaded=true;if(!Files.exists(file))return;try{for(String l:Files.readAllLines(file,StandardCharsets.UTF_8).stream().skip(1).toList()){List<String> c=CsvUtil.parse(l);if(c.size()<12)continue;rows.add(new TrackerTrip(c.get(0),c.get(1),c.get(2),c.get(3),c.get(4),c.get(5),c.get(6),c.get(7),c.get(8),CsvUtil.i(c.get(9),0),c.get(10),c.get(11)));}}catch(Exception ignored){}}
 private void save(){try{Files.createDirectories(file.getParent());StringBuilder b=new StringBuilder("Id,DeviceId,TrailerId,ShipmentId,DestinationId,State,AssignedAt,ScheduledArrival,EstimatedArrival,DelayMinutes,LastUpdated,Notes\n");for(TrackerTrip t:rows)b.append(String.join(",",CsvUtil.q(t.id()),CsvUtil.q(t.deviceId()),CsvUtil.q(t.trailerId()),CsvUtil.q(t.shipmentId()),CsvUtil.q(t.destinationId()),CsvUtil.q(t.state()),CsvUtil.q(t.assignedAt()),CsvUtil.q(t.scheduledArrival()),CsvUtil.q(t.estimatedArrival()),CsvUtil.q(t.delayMinutes()),CsvUtil.q(t.lastUpdated()),CsvUtil.q(t.notes()))).append('\n');Files.writeString(file,b.toString(),StandardCharsets.UTF_8);}catch(Exception ignored){}}
}
