package com.wtm.ui;
import javax.swing.*;import java.awt.*;import java.lang.reflect.*;import java.util.*;
/** Adds Data Collection as a first-class workspace route with native sidebar behavior. */
public final class DataIngestionInjector{
 public static void start(){javax.swing.Timer t=new javax.swing.Timer(700,e->scan());t.setInitialDelay(900);t.start();}
 private static void scan(){for(Window w:Window.getWindows())if(w instanceof JFrame f&&f.isDisplayable()&&f.getClass().getName().equals("com.wtm.ui.OperationsWorkspaceFrame"))try{inject(f);}catch(Exception ignored){}}
 @SuppressWarnings("unchecked") private static void inject(JFrame f)throws Exception{JPanel side=sidebar(f);if(side==null)return;Field mf=f.getClass().getDeclaredField("sidebarRouteButtons");mf.setAccessible(true);Map<String,JButton> map=(Map<String,JButton>)mf.get(f);JButton b=map.get("Data Collection");if(b==null){Method create=f.getClass().getDeclaredMethod("createSidebarButton",String.class,boolean.class);create.setAccessible(true);b=(JButton)create.invoke(f,"▣  Data Collection",false);b.setName("northstar.collection.sidebar");JButton button=b;b.addActionListener(e->SwingUtilities.invokeLater(()->open(f)));map.put("Data Collection",b);int admin=adminIndex(side),insert=admin;while(insert>0&&side.getComponent(insert-1) instanceof Box.Filler)insert--;side.add(b,Math.max(0,insert));side.revalidate();side.repaint();}else if(!hasRouteListener(b)){b.addActionListener(e->SwingUtilities.invokeLater(()->open(f)));}}
 private static boolean hasRouteListener(JButton b){for(var l:b.getActionListeners())if(l.getClass().getName().contains("DataIngestionInjector"))return true;return false;}
 private static void open(JFrame f){try{Field af=f.getClass().getDeclaredField("activeWorkspaceRoute");af.setAccessible(true);af.set(f,"Data Collection");try{Method m=f.getClass().getDeclaredMethod("closeEmbeddedSettingsSession");m.setAccessible(true);m.invoke(f);}catch(Exception ignored){}Field hf=f.getClass().getDeclaredField("workspaceContentHost");hf.setAccessible(true);JPanel host=(JPanel)hf.get(f);host.removeAll();host.add(new DataCollectionPanel(),BorderLayout.CENTER);try{Method m=f.getClass().getDeclaredMethod("updateSidebarSelection");m.setAccessible(true);m.invoke(f);}catch(Exception ignored){}host.revalidate();host.repaint();}catch(Exception ex){JOptionPane.showMessageDialog(f,ex.getMessage());}}
 private static int adminIndex(JPanel p){for(int i=0;i<p.getComponentCount();i++)if(p.getComponent(i) instanceof JLabel l&&"ADMINISTRATION".equalsIgnoreCase(l.getText()))return i;return p.getComponentCount();}
 private static JPanel sidebar(Container c){for(Component x:c.getComponents()){if(x instanceof JScrollPane sp&&sp.getViewport().getView() instanceof JPanel p&&contains(p,"Dashboard"))return p;if(x instanceof Container ct){JPanel p=sidebar(ct);if(p!=null)return p;}}return null;}
 private static boolean contains(Container c,String t){for(Component x:c.getComponents()){if(x instanceof JButton b&&strip(b.getText()).equalsIgnoreCase(t))return true;if(x instanceof Container ct&&contains(ct,t))return true;}return false;}private static String strip(String s){return s==null?"":s.replaceAll("^[^A-Za-z0-9]+\\s*","").trim();}
}
