package com.wtm.ui;
import com.wtm.ingest.*;import javax.swing.*;import javax.swing.border.EmptyBorder;import javax.swing.table.DefaultTableModel;import java.awt.*;import java.nio.file.*;import java.time.*;import java.time.format.DateTimeFormatter;
public final class DataCollectionPanel extends JPanel {
 private final DataIngestionService service=DataIngestionService.get();private final DefaultTableModel feeds=new DefaultTableModel(new Object[]{"Domain","Data Feed","Status","Rows","Last Updated","Available to KPI Showcase"},0){public Class<?>getColumnClass(int c){return c==5?Boolean.class:String.class;}public boolean isCellEditable(int r,int c){return c==5;}};private boolean refreshing;
 public DataCollectionPanel(){super(new BorderLayout(12,12));setBackground(Theme.bg());setBorder(new EmptyBorder(18,18,18,18));add(header(),BorderLayout.NORTH);NorthStarTabHost tabs=new NorthStarTabHost();tabs.addTab("Data Sources",sources()).addTab("Import & Connections",new DataCollectionConnectionsPanel()).addTab("Import History",new DataCollectionHistoryPanel());add(tabs);refresh();NorthStarThemeCompliance.apply(this);}
 private JComponent header(){JPanel p=new JPanel(new BorderLayout(0,3));p.setOpaque(false);JLabel a=new JLabel("Data Collection");a.setForeground(Theme.text());a.setFont(new Font(Font.SANS_SERIF,Font.BOLD,25));JLabel b=new JLabel("Operational source hub • DVIEW exports are classified, validated, stored and made available to NorthStar Intelligence.");b.setForeground(Theme.muted());p.add(a,BorderLayout.NORTH);p.add(b,BorderLayout.SOUTH);return p;}
 private JComponent sources(){JPanel p=new JPanel(new BorderLayout(8,10));p.setBackground(Theme.bg());p.setBorder(new EmptyBorder(10,4,4,4));GlassSurfacePanel ex=new GlassSurfacePanel(14);ex.setLayout(new BorderLayout());ex.setBorder(new EmptyBorder(12,14,12,14));JLabel note=new JLabel("<html><b>Data Collection owns the data.</b> This checkbox only makes a feed eligible to supply KPI Showcase metrics. <b>Workspace Setup owns the KPI Showcase</b>: targets, direction, ordering, enabled cards and dashboard movement are configured there.</html>");note.setForeground(Theme.text());ex.add(note);p.add(ex,BorderLayout.NORTH);JTable t=new JTable(feeds);t.setRowHeight(30);t.setFillsViewportHeight(true);feeds.addTableModelListener(e->{if(refreshing)return;if(e.getColumn()==5&&e.getFirstRow()>=0&&e.getFirstRow()<OperationalDataCatalog.feeds().size()){Object v=feeds.getValueAt(e.getFirstRow(),5);if(v instanceof Boolean b)OperationalDataCatalog.setShowcase(OperationalDataCatalog.feeds().get(e.getFirstRow()).id(),b);}});p.add(new JScrollPane(t));JPanel s=new JPanel(new BorderLayout());s.setOpaque(false);JLabel l=new JLabel("Recognized feeds are routed by schema; unfamiliar structures are held for review instead of being guessed.");l.setForeground(Theme.muted());JButton r=new JButton("Refresh Sources");r.addActionListener(e->refresh());s.add(l);s.add(r,BorderLayout.EAST);p.add(s,BorderLayout.SOUTH);return p;}
 private void refresh(){refreshing=true;try{feeds.setRowCount(0);DateTimeFormatter fmt=DateTimeFormatter.ofPattern("MMM d, yyyy h:mm a");for(OperationalDataCatalog.Feed f:OperationalDataCatalog.feeds()){String st="Not loaded",rows="—",up="—";try{DataIngestionService.Type ty=DataIngestionService.Type.valueOf(f.id());Path p=service.dataFile(ty);if(Files.isRegularFile(p)){st="Ready";try(var x=Files.lines(p)){rows=String.valueOf(Math.max(0,x.count()-1));}up=LocalDateTime.ofInstant(Files.getLastModifiedTime(p).toInstant(),ZoneId.systemDefault()).format(fmt);}}catch(Exception e){}feeds.addRow(new Object[]{f.domain(),f.title(),st,rows,up,OperationalDataCatalog.showcase(f.id())});}}finally{refreshing=false;}NorthStarThemeCompliance.apply(this);revalidate();repaint();}
}
