package com.wtm.ui;
import com.wtm.ingest.*;import javax.swing.*;import javax.swing.border.EmptyBorder;import javax.swing.table.DefaultTableModel;import java.awt.*;import java.io.File;import java.nio.file.*;import java.util.*;import java.util.List;
public final class DataCollectionPanel extends JPanel{
 private final DataIngestionService service=DataIngestionService.get();private final DefaultTableModel feeds=new DefaultTableModel(new Object[]{"Domain","Data Feed","Status","Rows","Show in KPI Showcase"},0){public Class<?> getColumnClass(int c){return c==4?Boolean.class:String.class;}public boolean isCellEditable(int r,int c){return c==4;}};
 public DataCollectionPanel(){super(new BorderLayout(12,12));setBackground(Theme.bg());setBorder(new EmptyBorder(18,18,18,18));add(header(),BorderLayout.NORTH);JTabbedPane t=new JTabbedPane();t.addTab("Data Sources",sources());t.addTab("KPI Showcase",showcase());t.addTab("Import & Connections",new DataIngestionPanel());add(t);refresh();NorthStarThemeCompliance.apply(this);}
 private JComponent header(){JPanel p=new JPanel(new BorderLayout());p.setOpaque(false);JLabel a=new JLabel("Data Collection");a.setForeground(Theme.text());a.setFont(new Font(Font.SANS_SERIF,Font.BOLD,25));JLabel b=new JLabel("Operational source hub • DVIEW exports are classified, validated, stored and made available to NorthStar Intelligence.");b.setForeground(Theme.muted());p.add(a,BorderLayout.NORTH);p.add(b,BorderLayout.SOUTH);return p;}
 private JComponent sources(){JPanel p=page();JPanel top=new JPanel(new FlowLayout(FlowLayout.LEFT,8,0));top.setOpaque(false);JButton add=new JButton("Import Daily Data"),folder=new JButton("Open Incoming Folder"),refresh=new JButton("Refresh");top.add(add);top.add(folder);top.add(refresh);p.add(top,BorderLayout.NORTH);JTable table=new JTable(feeds);table.setRowHeight(28);table.setFillsViewportHeight(true);feeds.addTableModelListener(e->{if(e.getColumn()==4&&e.getFirstRow()>=0&&e.getFirstRow()<OperationalDataCatalog.feeds().size()){OperationalDataCatalog.Feed f=OperationalDataCatalog.feeds().get(e.getFirstRow());Object v=feeds.getValueAt(e.getFirstRow(),4);if(v instanceof Boolean b)OperationalDataCatalog.setShowcase(f.id(),b);}});JScrollPane sp=new JScrollPane(table);sp.getVerticalScrollBar().setUnitIncrement(18);p.add(sp);add.addActionListener(e->choose(p));folder.addActionListener(e->{try{Desktop.getDesktop().open(service.incoming().toFile());}catch(Exception ex){}});refresh.addActionListener(e->refresh());return p;}
 private JComponent showcase(){JPanel p=page();GlassSurfacePanel card=new GlassSurfacePanel(16);card.setLayout(new BorderLayout());card.setBorder(new EmptyBorder(18,18,18,18));JTextArea info=new JTextArea("KPI Main Showcase is an optional presentation layer, not the operational data store.\n\nUse the checkboxes in Data Sources to choose which operational feeds are eligible for dashboard presentation. NorthStar Intelligence can still use authorized imported feeds even when they are hidden from the showcase.\n\nRecommended defaults: Daily LHY & LPH, Hourly Picks, and Floor Denials. Audit traces, equipment history, exception investigation and tracker feeds remain available to Intelligence without cluttering the main dashboard.");info.setEditable(false);info.setOpaque(false);info.setForeground(Theme.text());info.setLineWrap(true);info.setWrapStyleWord(true);card.add(info);p.add(card);return p;}
 private JPanel page(){JPanel p=new JPanel(new BorderLayout(8,8));p.setBackground(Theme.bg());p.setBorder(new EmptyBorder(12,4,4,4));return p;}
 private void choose(Component c){JFileChooser fc=new JFileChooser();fc.setMultiSelectionEnabled(true);if(fc.showOpenDialog(c)==JFileChooser.APPROVE_OPTION)for(File f:fc.getSelectedFiles())try{service.importFile(f.toPath(),"Data Collection");}catch(Exception ex){JOptionPane.showMessageDialog(c,ex.getMessage());}refresh();NorthStarThemeCompliance.apply(this);}
 private void refresh(){feeds.setRowCount(0);for(OperationalDataCatalog.Feed f:OperationalDataCatalog.feeds()){String status="Not loaded",rows="—";try{DataIngestionService.Type t=DataIngestionService.Type.valueOf(f.id());Path p=service.dataFile(t);if(Files.isRegularFile(p)){status="Ready";try(var s=Files.lines(p)){rows=String.valueOf(Math.max(0,s.count()-1));}}}catch(Exception ignored){}feeds.addRow(new Object[]{f.domain(),f.title(),status,rows,OperationalDataCatalog.showcase(f.id())});}}
}
