package com.wtm.ui;

import com.wtm.ingest.*;import javax.swing.*;import javax.swing.border.EmptyBorder;import javax.swing.table.DefaultTableModel;import java.awt.*;import java.awt.datatransfer.DataFlavor;import java.io.File;import java.nio.file.*;import java.util.List;

public final class DataIngestionPanel extends JPanel {
 private final DataIngestionService service=DataIngestionService.get(); private final DefaultTableModel model=new DefaultTableModel(new Object[]{"Received","Source","File","Detected Type","Status","Records","Message"},0);
 public DataIngestionPanel(){super(new BorderLayout(12,12));setBackground(Theme.bg());setBorder(new EmptyBorder(18,18,18,18));add(header(),BorderLayout.NORTH);JTabbedPane tabs=new JTabbedPane();tabs.addTab("Incoming Data",incoming());tabs.addTab("Import History",history());tabs.addTab("Connections",connections());add(tabs,BorderLayout.CENTER);refresh();}
 private JComponent header(){JPanel p=new JPanel(new BorderLayout());p.setOpaque(false);JPanel words=new JPanel();words.setOpaque(false);words.setLayout(new BoxLayout(words,BoxLayout.Y_AXIS));JLabel t=new JLabel("Data Ingestion");t.setForeground(Theme.text());t.setFont(new Font(Font.SANS_SERIF,Font.BOLD,25));JLabel d=new JLabel("One validation pipeline for manual files, watched folders, email attachments, and future enterprise feeds.");d.setForeground(Theme.muted());words.add(t);words.add(Box.createVerticalStrut(4));words.add(d);p.add(words);return p;}
 private JComponent incoming(){JPanel p=page();JPanel actions=new JPanel(new FlowLayout(FlowLayout.LEFT,8,0));actions.setOpaque(false);JButton upload=new JButton("Import CSV"),folder=new JButton("Open Incoming Folder"),scan=new JButton("Scan Now"),refresh=new JButton("Refresh");JCheckBox watch=new JCheckBox("Watch folder",service.watchEnabled()),auto=new JCheckBox("Validated auto-import",service.autoImport());for(AbstractButton b:new AbstractButton[]{upload,folder,scan,refresh,watch,auto}){b.setOpaque(false);b.setForeground(Theme.text());actions.add(b);}p.add(actions,BorderLayout.NORTH);JTable table=new JTable(model);table.setFillsViewportHeight(true);p.add(new JScrollPane(table),BorderLayout.CENTER);JLabel drop=new JLabel("Drop CSV files here • recognized schemas import automatically • unknown files are quarantined for review",SwingConstants.CENTER);drop.setForeground(Theme.muted());drop.setBorder(new EmptyBorder(12,6,6,6));p.add(drop,BorderLayout.SOUTH);upload.addActionListener(e->choose(p));folder.addActionListener(e->{try{Desktop.getDesktop().open(service.incoming().toFile());}catch(Exception ex){msg(p,ex.getMessage());}});scan.addActionListener(e->{service.scanIncoming();refresh();});refresh.addActionListener(e->refresh());watch.addActionListener(e->service.setWatchEnabled(watch.isSelected()));auto.addActionListener(e->service.setAutoImport(auto.isSelected()));new javax.swing.Timer(5000,e->{service.scanIncoming();refresh();}).start();setTransferHandler(new TransferHandler(){public boolean canImport(TransferSupport s){return s.isDataFlavorSupported(DataFlavor.javaFileListFlavor);}public boolean importData(TransferSupport s){try{for(File f:(List<File>)s.getTransferable().getTransferData(DataFlavor.javaFileListFlavor))service.importFile(f.toPath(),"Drag & Drop");refresh();return true;}catch(Exception e){msg(p,e.getMessage());return false;}}});return p;}
 private JComponent history(){JPanel p=page();JTextArea a=new JTextArea("Every import is logged with source, file hash, detected schema, result, record count, and archived source path. Exact duplicate files are blocked before they can be inserted twice.\n\nArchive: "+Path.of(System.getProperty("user.home"),".northstar-operations-intelligence","ingestion","archive")+"\nQuarantine: "+Path.of(System.getProperty("user.home"),".northstar-operations-intelligence","ingestion","quarantine"));a.setEditable(false);a.setLineWrap(true);a.setWrapStyleWord(true);a.setOpaque(false);a.setForeground(Theme.text());p.add(a);return p;}
 private JComponent connections(){JPanel p=page();JPanel stack=new JPanel();stack.setOpaque(false);stack.setLayout(new BoxLayout(stack,BoxLayout.Y_AXIS));stack.add(card("Manual File Import","AVAILABLE","Choose or drag/drop CSV exports directly into NorthStar."));stack.add(Box.createVerticalStrut(10));stack.add(card("Watched Folder","AVAILABLE",service.incoming().toString()));stack.add(Box.createVerticalStrut(10));stack.add(card("Test Email Connector","PLANNED / OPTIONAL","Provider-neutral test connector can feed attachments into this same pipeline."));stack.add(Box.createVerticalStrut(10));stack.add(card("Microsoft 365 / Graph","ENTERPRISE READY · REQUIRES IT AUTHORIZATION","Designed as the production target. No company credentials, tenant access, or Graph permissions are requested by this prototype."));p.add(new JScrollPane(stack));return p;}
 private JPanel card(String title,String state,String text){RoundedPanel r=new RoundedPanel(14);r.setLayout(new BorderLayout(12,5));r.setBackground(Theme.panel());r.setBorder(new EmptyBorder(14,16,14,16));JLabel t=new JLabel(title+"   •   "+state);t.setForeground(Theme.text());t.setFont(new Font(Font.SANS_SERIF,Font.BOLD,13));JLabel d=new JLabel("<html>"+text+"</html>");d.setForeground(Theme.muted());r.add(t,BorderLayout.NORTH);r.add(d);r.setMaximumSize(new Dimension(Integer.MAX_VALUE,90));return r;}
 private JPanel page(){JPanel p=new JPanel(new BorderLayout(8,8));p.setBackground(Theme.bg());p.setBorder(new EmptyBorder(12,4,4,4));return p;}
 private void choose(Component owner){JFileChooser fc=new JFileChooser();fc.setMultiSelectionEnabled(true);if(fc.showOpenDialog(owner)==JFileChooser.APPROVE_OPTION)for(File f:fc.getSelectedFiles())try{IngestionRecord r=service.importFile(f.toPath(),"Manual Upload");msg(owner,r.status()+" — "+r.detectedType()+" — "+r.records()+" records");}catch(Exception ex){msg(owner,ex.getMessage());}refresh();}
 private void refresh(){model.setRowCount(0);List<IngestionRecord> h=service.history();for(int i=h.size()-1;i>=0&&i>=h.size()-250;i--){IngestionRecord r=h.get(i);model.addRow(new Object[]{r.receivedAt(),r.source(),r.originalName(),r.detectedType(),r.status(),r.records(),r.message()});}}
 private static void msg(Component c,String s){JOptionPane.showMessageDialog(c,s==null?"Unknown error":s,"NorthStar Data Ingestion",JOptionPane.INFORMATION_MESSAGE);}
}
