package com.wtm.ui;

import com.wtm.ingest.*;import javax.swing.*;import javax.swing.border.EmptyBorder;import javax.swing.table.DefaultTableModel;import java.awt.*;import java.nio.file.*;import java.time.*;import java.time.format.DateTimeFormatter;

public final class DataCollectionPanel extends JPanel{
 private final DataIngestionService service=DataIngestionService.get();
 private final DefaultTableModel feeds=new DefaultTableModel(new Object[]{"Domain","Data Feed","Status","Rows","Last Updated","Available to KPI Showcase"},0){public Class<?>getColumnClass(int c){return c==5?Boolean.class:String.class;}public boolean isCellEditable(int r,int c){return c==5;}};
 private boolean refreshing;
 public DataCollectionPanel(){super(new BorderLayout(12,12));setBackground(Theme.bg());setBorder(new EmptyBorder(18,18,18,18));add(header(),BorderLayout.NORTH);JTabbedPane tabs=NorthStarTabs.create();NorthStarTabs.add(tabs,"Data Sources",sources());NorthStarTabs.add(tabs,"Import & Connections",new DataCollectionConnectionsPanel());NorthStarTabs.add(tabs,"Import History",new DataCollectionHistoryPanel());add(tabs,BorderLayout.CENTER);refresh();NorthStarThemeCompliance.apply(this);NorthStarTabs.refreshHeaders(tabs);}
 private JComponent header(){JPanel p=new JPanel(new BorderLayout(0,3));p.setOpaque(false);JLabel a=new JLabel("Data Collection");a.setForeground(Theme.text());a.setFont(new Font(Font.SANS_SERIF,Font.BOLD,25));JLabel b=new JLabel("Operational source hub • DVIEW exports are classified, validated, stored and made available to NorthStar Intelligence.");b.setForeground(Theme.muted());p.add(a,BorderLayout.NORTH);p.add(b,BorderLayout.SOUTH);return p;}
 private JComponent sources(){JPanel p=page();GlassSurfacePanel explanation=new GlassSurfacePanel(14);explanation.setLayout(new BorderLayout());explanation.setBorder(new EmptyBorder(12,14,12,14));JLabel note=new JLabel("<html><b>Data Collection owns the data.</b> The checkbox only makes a feed eligible to supply KPI Showcase metrics. <b>Workspace Setup owns the KPI Showcase</b>: targets, direction, ordering, enabled cards and dashboard movement are configured there. Intelligence can still use authorized imported feeds that are hidden from the dashboard.</html>");note.setForeground(Theme.text());explanation.add(note);p.add(explanation,BorderLayout.NORTH);JTable table=new JTable(feeds);table.setRowHeight(30);table.setFillsViewportHeight(true);feeds.addTableModelListener(e->{if(refreshing)return;if(e.getColumn()==5&&e.getFirstRow()>=0&&e.getFirstRow()<OperationalDataCatalog.feeds().size()){Object v=feeds.getValueAt(e.getFirstRow(),5);if(v instanceof Boolean b)OperationalDataCatalog.setShowcase(OperationalDataCatalog.feeds().get(e.getFirstRow()).id(),b);}});JScrollPane sp=new JScrollPane(table);sp.getVerticalScrollBar().setUnitIncrement(18);p.add(sp);JPanel south=new JPanel(new BorderLayout());south.setOpaque(false);JLabel schema=new JLabel("Recognized feeds are routed by schema; unfamiliar structures are held for review instead of being interpreted automatically.");schema.setForeground(Theme.muted());JButton refresh=new JButton("Refresh Sources");refresh.addActionListener(e->refresh());south.add(schema);south.add(refresh,BorderLayout.EAST);p.add(south,BorderLayout.SOUTH);return p;}
 private JPanel page(){JPanel p=new JPanel(new BorderLayout(8,10));p.setBackground(Theme.bg());p.setBorder(new EmptyBorder(10,4,4,4));return p;}
 private void refresh(){refreshing=true;try{feeds.setRowCount(0);DateTimeFormatter fmt=DateTimeFormatter.ofPattern("MMM d, yyyy h:mm a");for(OperationalDataCatalog.Feed f:OperationalDataCatalog.feeds()){String status="Not loaded",rows="—",updated="—";try{DataIngestionService.Type t=DataIngestionService.Type.valueOf(f.id());Path file=service.dataFile(t);if(Files.isRegularFile(file)){status="Ready";try(var s=Files.lines(file)){rows=String.valueOf(Math.max(0,s.count()-1));}updated=LocalDateTime.ofInstant(Files.getLastModifiedTime(file).toInstant(),ZoneId.systemDefault()).format(fmt);}}catch(Exception ignored){}feeds.addRow(new Object[]{f.domain(),f.title(),status,rows,updated,OperationalDataCatalog.showcase(f.id())});}}finally{refreshing=false;}NorthStarThemeCompliance.apply(this);revalidate();repaint();}
}
