package com.wtm.ui;
import com.wtm.ingest.*;import javax.swing.*;import javax.swing.border.EmptyBorder;import java.awt.*;
public final class DataCollectionConnectionsPanel extends JPanel {
 private final DataIngestionService service=DataIngestionService.get(); private final GmailDataPathService gmail=GmailDataPathService.get(); private JLabel status;
 public DataCollectionConnectionsPanel(){super(new BorderLayout(10,10));setBackground(Theme.bg());setBorder(new EmptyBorder(12,4,4,4));JPanel stack=new JPanel();stack.setOpaque(false);stack.setLayout(new BoxLayout(stack,BoxLayout.Y_AXIS));stack.add(importCard());stack.add(Box.createVerticalStrut(10));stack.add(gmailCard());JScrollPane sp=new JScrollPane(stack);sp.setBorder(null);sp.getVerticalScrollBar().setUnitIncrement(20);add(sp);NorthStarThemeCompliance.apply(this);}
 private JComponent importCard(){GlassSurfacePanel r=new GlassSurfacePanel(16);r.setLayout(new BorderLayout(8,8));r.setBorder(new EmptyBorder(16,16,16,16));JLabel h=new JLabel("FILE & DVIEW EXPORT INGESTION");h.setForeground(Theme.text());h.setFont(new Font(Font.SANS_SERIF,Font.BOLD,13));r.add(h,BorderLayout.NORTH);JPanel b=new JPanel();b.setOpaque(false);b.setLayout(new BoxLayout(b,BoxLayout.Y_AXIS));JLabel d=new JLabel("<html>Import one CSV or a sectioned NorthStar bundle containing several DVIEW result sets. Each section is validated independently.</html>");d.setForeground(Theme.muted());b.add(d);b.add(Box.createVerticalStrut(10));JPanel a=new JPanel(new FlowLayout(FlowLayout.LEFT,8,0));a.setOpaque(false);JButton csv=new JButton("Import CSV"),bundle=new JButton("Import NorthStar Bundle"),folder=new JButton("Open Incoming Folder"),scan=new JButton("Scan Folder Now");a.add(csv);a.add(bundle);a.add(folder);a.add(scan);b.add(a);b.add(Box.createVerticalStrut(10));JPanel o=new JPanel(new FlowLayout(FlowLayout.LEFT,8,0));o.setOpaque(false);JCheckBox watch=new JCheckBox("Watch incoming folder",service.watchEnabled()),auto=new JCheckBox("Validated auto-import",service.autoImport());watch.setOpaque(false);auto.setOpaque(false);o.add(watch);o.add(auto);b.add(o);JLabel f=new JLabel("Bundle format: __NORTHSTAR_DATASET__,<name> ... CSV ... __END_DATASET__");f.setForeground(Theme.muted());b.add(f);r.add(b);csv.addActionListener(e->csv(r));bundle.addActionListener(e->bundle(r));folder.addActionListener(e->{try{Desktop.getDesktop().open(service.incoming().toFile());}catch(Exception ex){msg(r,ex.getMessage());}});scan.addActionListener(e->{service.scanIncoming();msg(r,"Incoming folder scan complete.");});watch.addActionListener(e->service.setWatchEnabled(watch.isSelected()));auto.addActionListener(e->service.setAutoImport(auto.isSelected()));return r;}
 private JComponent gmailCard(){GlassSurfacePanel r=new GlassSurfacePanel(16);r.setLayout(new BorderLayout(8,8));r.setBorder(new EmptyBorder(16,16,16,16));JPanel head=new JPanel(new BorderLayout());head.setOpaque(false);JLabel h=new JLabel("GMAIL DATAPATH • DEVELOPMENT CONNECTOR");h.setForeground(Theme.text());h.setFont(new Font(Font.SANS_SERIF,Font.BOLD,13));status=new JLabel();head.add(h);head.add(status,BorderLayout.EAST);r.add(head,BorderLayout.NORTH);JPanel b=new JPanel(new FlowLayout(FlowLayout.LEFT,8,0));b.setOpaque(false);JButton client=new JButton("Choose OAuth JSON"),connect=new JButton("Connect Gmail"),check=new JButton("Check Now");b.add(client);b.add(connect);b.add(check);r.add(b);Runnable st=()->{var s=gmail.status();status.setText(s.connected()?"● CONNECTED • "+s.mailbox():s.configured()?"● READY TO AUTHORIZE":"○ NOT CONFIGURED");status.setForeground(s.connected()?new Color(40,205,150):Theme.muted());};st.run();client.addActionListener(e->{java.nio.file.Path p=NorthStarFileDialog.open(r,"Select Google OAuth JSON","json");if(p!=null)try{gmail.installClientJson(p);st.run();}catch(Exception ex){msg(r,ex.getMessage());}});connect.addActionListener(e->{new SwingWorker<String,Void>(){protected String doInBackground()throws Exception{return gmail.connectInteractive();}protected void done(){try{msg(r,"Connected to "+get());}catch(Exception ex){msg(r,root(ex));}st.run();}}.execute();});check.addActionListener(e->{new SwingWorker<GmailDataPathService.SyncResult,Void>(){protected GmailDataPathService.SyncResult doInBackground()throws Exception{return gmail.syncNow();}protected void done(){try{var x=get();msg(r,"Imported: "+x.imported()+" • Review/duplicate: "+x.duplicateOrReview());}catch(Exception ex){msg(r,root(ex));}st.run();}}.execute();});return r;}
 private void csv(Component c){java.nio.file.Path p=NorthStarFileDialog.open(c,"Import NorthStar CSV","csv");if(p!=null)try{IngestionRecord r=service.importFile(p,"Data Collection");msg(c,r.status()+" • "+r.detectedType()+" • "+r.records()+" rows");}catch(Exception e){msg(c,e.getMessage());}}
 private void bundle(Component c){java.nio.file.Path p=NorthStarFileDialog.open(c,"Import NorthStar Bundle","csv","txt");if(p!=null)try{var r=SectionedImportService.importBundle(p,"NorthStar Bundle");msg(c,"Sections: "+r.sections()+" • Imported: "+r.imported()+" • Review: "+r.review());}catch(Exception e){msg(c,e.getMessage());}} private static String root(Throwable t){Throwable x=t;while(x.getCause()!=null)x=x.getCause();return x.getMessage();}private static void msg(Component c,String s){JOptionPane.showMessageDialog(c,s,"NorthStar Data Collection",JOptionPane.INFORMATION_MESSAGE);}
}
