package com.wtm.ui;
import javax.swing.*;import java.awt.*;import java.lang.reflect.*;import java.util.Map;
public final class DataIngestionInjector{
 private DataIngestionInjector(){}public static void start(){Timer t=new Timer(900,e->scan());t.setInitialDelay(1500);t.start();}
 private static void scan(){for(Window w:Window.getWindows())if(w instanceof JFrame f&&f.isDisplayable()&&f.getClass().getName().equals("com.wtm.ui.OperationsWorkspaceFrame"))try{inject(f);}catch(Exception ignored){}}
 @SuppressWarnings("unchecked")private static void inject(JFrame frame)throws Exception{if(find(frame,"northstar.collection.sidebar")!=null)return;JPanel side=findSidebar(frame);if(side==null)return;Method create=frame.getClass().getDeclaredMethod("createSidebarButton",String.class,boolean.class);create.setAccessible(true);JButton b=(JButton)create.invoke(frame,"▣  Data Collection",false);b.setName("northstar.collection.sidebar");b.addActionListener(e->open(frame));Field rf=frame.getClass().getDeclaredField("sidebarRouteButtons");rf.setAccessible(true);Object raw=rf.get(frame);if(raw instanceof Map<?,?>m)((Map<String,JButton>)m).put("Data Collection",b);int admin=side.getComponentCount();for(int i=0;i<side.getComponentCount();i++)if(side.getComponent(i)instanceof JLabel l&&"ADMINISTRATION".equalsIgnoreCase(l.getText())){admin=i;break;}side.add(b,Math.max(0,admin));side.revalidate();side.repaint();}
 private static void open(JFrame f){try{Field hf=f.getClass().getDeclaredField("workspaceContentHost");hf.setAccessible(true);JPanel host=(JPanel)hf.get(f);try{Field ar=f.getClass().getDeclaredField("activeWorkspaceRoute");ar.setAccessible(true);ar.set(f,"Data Collection");}catch(Exception ignored){}host.removeAll();host.add(new DataCollectionPanel(),BorderLayout.CENTER);host.revalidate();host.repaint();try{Method m=f.getClass().getDeclaredMethod("updateSidebarSelection");m.setAccessible(true);m.invoke(f);}catch(Exception ignored){}}catch(Exception ex){JOptionPane.showMessageDialog(f,"Unable to open Data Collection.\n"+ex.getMessage());}}
 private static JPanel findSidebar(Container r){for(Component c:r.getComponents()){if(c instanceof JScrollPane s&&s.getViewport().getView()instanceof JPanel p&&hasDashboard(p))return p;if(c instanceof Container ct){JPanel p=findSidebar(ct);if(p!=null)return p;}}return null;}private static boolean hasDashboard(Container c){for(Component x:c.getComponents())if(x instanceof JButton b&&b.getText()!=null&&b.getText().contains("Dashboard"))return true;return false;}private static Component find(Container r,String n){for(Component c:r.getComponents()){if(n.equals(c.getName()))return c;if(c instanceof Container ct){Component x=find(ct,n);if(x!=null)return x;}}return null;}
}
