package com.wtm.ui;
import com.wtm.ai.NorthStarIntelligenceService; import javax.swing.*; import javax.swing.border.EmptyBorder; import java.awt.*; import java.nio.charset.StandardCharsets; import java.nio.file.*; import java.util.*;
public final class IntelligenceAnalysisDialog extends JDialog {
 public IntelligenceAnalysisDialog(Window owner,String question,NorthStarIntelligenceService.Answer answer){super(owner,"NorthStar Intelligence Analysis",ModalityType.MODELESS);setDefaultCloseOperation(DISPOSE_ON_CLOSE);setSize(1120,760);setMinimumSize(new Dimension(860,600));setLocationRelativeTo(owner);setContentPane(build(question,answer));}
 private JComponent build(String q,NorthStarIntelligenceService.Answer a){JPanel root=new JPanel(new BorderLayout());root.setBackground(new Color(8,11,18));root.setBorder(new EmptyBorder(22,22,22,22));GlassSurfacePanel shell=new GlassSurfacePanel(24);shell.setLayout(new BorderLayout(18,18));shell.setBorder(new EmptyBorder(20,22,20,22));JPanel head=new JPanel(new BorderLayout());head.setOpaque(false);JPanel words=new JPanel();words.setOpaque(false);words.setLayout(new BoxLayout(words,BoxLayout.Y_AXIS));JLabel t=new JLabel("NORTHSTAR INTELLIGENCE");t.setForeground(Theme.text());t.setFont(new Font(Font.SANS_SERIF,Font.BOLD,20));JLabel sub=new JLabel("Analysis • "+shorten(q,105));sub.setForeground(Theme.muted());sub.setFont(new Font(Font.SANS_SERIF,Font.PLAIN,12));words.add(t);words.add(Box.createVerticalStrut(4));words.add(sub);head.add(words,BorderLayout.WEST);JPanel controls=new JPanel(new FlowLayout(FlowLayout.RIGHT,7,0));controls.setOpaque(false);JToggleButton glass=new JToggleButton("Glass",IntelligenceGlassSettings.enabled());glass.addActionListener(e->{IntelligenceGlassSettings.setEnabled(glass.isSelected());repaint();});JButton close=new JButton("Close");close.addActionListener(e->dispose());controls.add(glass);controls.add(close);head.add(controls,BorderLayout.EAST);shell.add(head,BorderLayout.NORTH);JPanel content=new JPanel(new GridLayout(1,2,16,0));content.setOpaque(false);content.add(summaryCard(a));content.add(visualCard(q));shell.add(content,BorderLayout.CENTER);shell.add(sourceBar(a),BorderLayout.SOUTH);root.add(shell,BorderLayout.CENTER);return root;}
 private JComponent summaryCard(NorthStarIntelligenceService.Answer a){GlassSurfacePanel p=new GlassSurfacePanel(18);p.setLayout(new BorderLayout(0,10));p.setBorder(new EmptyBorder(18,18,18,18));JLabel title=new JLabel("AI SUMMARY");title.setForeground(Theme.text());title.setFont(new Font(Font.SANS_SERIF,Font.BOLD,12));p.add(title,BorderLayout.NORTH);JTextArea text=new JTextArea(a.text());text.setEditable(false);text.setLineWrap(true);text.setWrapStyleWord(true);text.setOpaque(false);text.setForeground(Theme.text());text.setFont(new Font(Font.SANS_SERIF,Font.PLAIN,14));JScrollPane s=new JScrollPane(text);s.setOpaque(false);s.getViewport().setOpaque(false);s.setBorder(null);p.add(s,BorderLayout.CENTER);return p;}
 private JComponent visualCard(String q){GlassSurfacePanel p=new GlassSurfacePanel(18);p.setLayout(new BorderLayout(0,10));p.setBorder(new EmptyBorder(18,18,18,18));JLabel title=new JLabel("OPERATIONAL EVIDENCE");title.setForeground(Theme.text());title.setFont(new Font(Font.SANS_SERIF,Font.BOLD,12));p.add(title,BorderLayout.NORTH);Trend tr=findLhy();if(tr.values.size()>=2&&(q.toLowerCase().contains("lhy")||q.toLowerCase().contains("trend")||q.toLowerCase().contains("performance"))){JPanel body=new JPanel(new BorderLayout(0,10));body.setOpaque(false);JPanel metrics=new JPanel(new GridLayout(1,3,8,0));metrics.setOpaque(false);double latest=tr.values.get(tr.values.size()-1),avg=tr.values.stream().mapToDouble(Double::doubleValue).average().orElse(0);metrics.add(metric("LATEST",latest));metrics.add(metric("RECENT AVG",avg));metrics.add(metric("VS 17,500",avg-17500));body.add(metrics,BorderLayout.NORTH);body.add(new IntelligenceTrendChart(tr.values,tr.labels,17500),BorderLayout.CENTER);p.add(body,BorderLayout.CENTER);}else{JTextArea n=new JTextArea("NorthStar will place charts, tables, route history, document evidence, or KPI cards here when the selected data supports a visualization.\n\nFor LHY analysis, import or retain LHY/KPI CSV history in the NorthStar application-data folder.");n.setLineWrap(true);n.setWrapStyleWord(true);n.setEditable(false);n.setOpaque(false);n.setForeground(Theme.muted());n.setFont(new Font(Font.SANS_SERIF,Font.PLAIN,13));p.add(n,BorderLayout.CENTER);}return p;}
 private JComponent metric(String label,double val){GlassSurfacePanel p=new GlassSurfacePanel(14);p.setLayout(new BoxLayout(p,BoxLayout.Y_AXIS));p.setBorder(new EmptyBorder(9,11,9,11));JLabel l=new JLabel(label);l.setForeground(Theme.muted());l.setFont(new Font(Font.SANS_SERIF,Font.BOLD,9));JLabel v=new JLabel(String.format("%,.0f",val));v.setForeground(Theme.text());v.setFont(new Font(Font.SANS_SERIF,Font.BOLD,20));p.add(l);p.add(Box.createVerticalStrut(3));p.add(v);return p;}
 private JComponent sourceBar(NorthStarIntelligenceService.Answer a){JPanel p=new JPanel(new BorderLayout());p.setOpaque(false);String s=(a.sources()==null||a.sources().isEmpty())?"No source files cited":"Sources • "+String.join("  •  ",a.sources());JLabel l=new JLabel(shorten(s,150));l.setForeground(Theme.muted());l.setFont(new Font(Font.SANS_SERIF,Font.PLAIN,10));p.add(l,BorderLayout.WEST);return p;}
 private record Trend(java.util.List<Double> values,java.util.List<String> labels){}
 private Trend findLhy(){Path root=Path.of(System.getProperty("user.home"),".northstar-operations-intelligence");java.util.List<Double> vals=new ArrayList<>();java.util.List<String> labels=new ArrayList<>();if(!Files.isDirectory(root))return new Trend(vals,labels);try(var stream=Files.walk(root,3)){for(Path f:stream.filter(Files::isRegularFile).filter(p->p.getFileName().toString().toLowerCase().endsWith(".csv")).toList()){String name=f.getFileName().toString().toLowerCase();if(!name.contains("lhy")&&!name.contains("kpi"))continue;for(String line:Files.readAllLines(f,StandardCharsets.UTF_8)){String[] c=line.split(",");Double found=null;for(String x:c){try{double d=Double.parseDouble(x.replace("\"","").trim());if(d>100&&d<1_000_000)found=d;}catch(Exception ignored){}}if(found!=null){vals.add(found);labels.add(c.length>0?shorten(c[0].replace("\"",""),8):Integer.toString(vals.size()));if(vals.size()>=20)break;}}if(vals.size()>=2)break;}}catch(Exception ignored){}return new Trend(vals,labels);}
 private static String shorten(String s,int n){if(s==null)return "";return s.length()>n?s.substring(0,n-1)+"…":s;}
}
