package com.wtm.ui;
import com.wtm.firstparty.*;import com.wtm.map.TileMapPanel;import java.awt.*;import java.lang.reflect.*;import java.util.*;import java.util.List;
public final class NetworkOverlayPainter{
 public static void paint(Graphics2D g,TileMapPanel map,int w,int h,boolean playback,Set<String>forced){g=(Graphics2D)g.create();g.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);try{double clat=(double)field(map,"centerLat"),clon=(double)field(map,"centerLon");int z=(int)field(map,"zoom");List<NetworkLocation> all=NetworkLocationStore.get().all();if(playback?NetworkMapDisplaySettings.playbackRegions():NetworkMapDisplaySettings.mainRegions())regions(g,all,clat,clon,z,w,h);for(NetworkLocation n:all){if(!n.active()||!n.hasCoordinates())continue;boolean force=matchesForced(n,forced),show=force||NetworkMapDisplaySettings.show(n.category(),playback);if(!show)continue;Point p=point(n.latitude(),n.longitude(),clat,clon,z,w,h);pin(g,p,NetworkPinStyleRegistry.style(n.category()),n.name(),force);}}catch(Exception ignored){}g.dispose();}
 private static boolean matchesForced(NetworkLocation n,Set<String> forced){if(forced==null||forced.isEmpty())return false;String a=(n.name()+" "+n.externalId()).toLowerCase(Locale.ROOT);for(String f:forced)if(f!=null&&!f.isBlank()&&a.contains(f.toLowerCase(Locale.ROOT)))return true;return false;}
 private static void regions(Graphics2D g,List<NetworkLocation> all,double clat,double clon,int z,int w,int h){Map<String,List<Point>>groups=new LinkedHashMap<>();for(NetworkLocation n:all){if(!n.active()||!n.hasCoordinates()||!n.category().toLowerCase().contains("dealer"))continue;String f=FacingCenterStore.get(n);if(f.isBlank())continue;groups.computeIfAbsent(f,k->new ArrayList<>()).add(point(n.latitude(),n.longitude(),clat,clon,z,w,h));}for(var e:groups.entrySet()){List<Point> hull=hull(e.getValue());if(hull.size()<3)continue;Polygon p=new Polygon();for(Point q:hull)p.addPoint(q.x,q.y);Color a=Theme.accent();g.setColor(new Color(a.getRed(),a.getGreen(),a.getBlue(),42));g.fillPolygon(p);g.setColor(new Color(a.getRed(),a.getGreen(),a.getBlue(),150));g.setStroke(new BasicStroke(2f));g.drawPolygon(p);Rectangle b=p.getBounds();g.setColor(Theme.text());g.drawString("Facing "+e.getKey(),b.x+8,b.y+18);}}
 private static List<Point> hull(List<Point> pts){List<Point>p=new ArrayList<>(new LinkedHashSet<>(pts));p.sort(Comparator.<Point>comparingInt(x->x.x).thenComparingInt(x->x.y));if(p.size()<3)return p;List<Point>lo=new ArrayList<>(),up=new ArrayList<>();for(Point q:p){while(lo.size()>=2&&cross(lo.get(lo.size()-2),lo.get(lo.size()-1),q)<=0)lo.remove(lo.size()-1);lo.add(q);}for(int i=p.size()-1;i>=0;i--){Point q=p.get(i);while(up.size()>=2&&cross(up.get(up.size()-2),up.get(up.size()-1),q)<=0)up.remove(up.size()-1);up.add(q);}lo.remove(lo.size()-1);up.remove(up.size()-1);lo.addAll(up);return lo;}private static long cross(Point a,Point b,Point c){return(long)(b.x-a.x)*(c.y-a.y)-(long)(b.y-a.y)*(c.x-a.x);}
 public static Point point(double lat,double lon,double clat,double clon,int z,int w,int h){double scale=256*Math.pow(2,z),wx=(lon+180)/360*scale,cx=(clon+180)/360*scale;double wy=(1-Math.log(Math.tan(Math.toRadians(lat))+1/Math.cos(Math.toRadians(lat)))/Math.PI)/2*scale,cy=(1-Math.log(Math.tan(Math.toRadians(clat))+1/Math.cos(Math.toRadians(clat)))/Math.PI)/2*scale;return new Point((int)Math.round(w/2+wx-cx),(int)Math.round(h/2+wy-cy));}
 private static Object field(Object o,String n)throws Exception{Field f=o.getClass().getDeclaredField(n);f.setAccessible(true);return f.get(o);}private static void pin(Graphics2D g,Point p,String style,String label,boolean forced){int x=p.x,y=p.y;g.setColor(forced?Theme.good():Theme.accent());switch(style){case"Square"->g.fillRoundRect(x-7,y-7,14,14,4,4);case"Diamond"->{Polygon q=new Polygon(new int[]{x,x+8,x,x-8},new int[]{y-9,y,y+9,y},4);g.fillPolygon(q);}case"Triangle"->{Polygon q=new Polygon(new int[]{x,x+8,x-8},new int[]{y-9,y+7,y+7},3);g.fillPolygon(q);}case"Star"->{Polygon q=new Polygon();for(int i=0;i<10;i++){double a=-Math.PI/2+i*Math.PI/5,r=i%2==0?9:4;q.addPoint((int)(x+Math.cos(a)*r),(int)(y+Math.sin(a)*r));}g.fillPolygon(q);}case"Home"->{g.fillRect(x-6,y-2,12,9);Polygon q=new Polygon(new int[]{x-9,x,x+9},new int[]{y-2,y-10,y-2},3);g.fillPolygon(q);}case"Dealer Dot"->{g.fillOval(x-7,y-7,14,14);g.setColor(Theme.text());g.fillOval(x-2,y-2,4,4);}default->g.fillOval(x-7,y-7,14,14);}g.setColor(Theme.text());g.drawString(label,x+11,y-8);}private NetworkOverlayPainter(){}
}
