package com.wtm.ui;
import javax.swing.*;import javax.swing.border.*;import javax.swing.plaf.basic.BasicTabbedPaneUI;import java.awt.*;import java.awt.event.*;
/** Canonical styling bridge for all legacy JTabbedPane workspaces. */
public final class NorthStarTabs{
 private static final int TAB_H=27,HPAD=11;
 public static JTabbedPane create(){JTabbedPane t=new JTabbedPane(JTabbedPane.TOP,JTabbedPane.SCROLL_TAB_LAYOUT);configure(t);t.addChangeListener(e->refreshHeaders(t));return t;}
 public static void configure(JTabbedPane t){t.setTabLayoutPolicy(JTabbedPane.SCROLL_TAB_LAYOUT);t.setOpaque(false);t.setBackground(Theme.bg());t.setForeground(Theme.text());t.setBorder(new EmptyBorder(1,0,0,0));if(!(t.getUI() instanceof CanonicalUI))t.setUI(new CanonicalUI());}
 public static void add(JTabbedPane t,String title,JComponent content){t.addTab(title,content);installHeader(t,t.getTabCount()-1,title);refreshHeaders(t);}
 private static void installHeader(JTabbedPane t,int i,String title){JLabel l=new JLabel(title,SwingConstants.CENTER);l.setOpaque(true);l.setFont(new Font(Font.SANS_SERIF,Font.PLAIN,12));int tw=l.getFontMetrics(l.getFont()).stringWidth(title),w=Math.max(58,Math.min(215,tw+HPAD*2));Dimension d=new Dimension(w,TAB_H);l.setPreferredSize(d);l.setMinimumSize(d);l.setMaximumSize(d);l.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));l.addMouseListener(new MouseAdapter(){public void mousePressed(MouseEvent e){int at=indexOf(t,l);if(at>=0)t.setSelectedIndex(at);}public void mouseEntered(MouseEvent e){style(l,indexOf(t,l)==t.getSelectedIndex(),true);}public void mouseExited(MouseEvent e){style(l,indexOf(t,l)==t.getSelectedIndex(),false);}});t.setTabComponentAt(i,l);}
 private static int indexOf(JTabbedPane t,Component c){for(int i=0;i<t.getTabCount();i++)if(t.getTabComponentAt(i)==c)return i;return-1;}
 public static void refreshHeaders(JTabbedPane t){configure(t);for(int i=0;i<t.getTabCount();i++){Component c=t.getTabComponentAt(i);if(!(c instanceof JLabel)){installHeader(t,i,t.getTitleAt(i));c=t.getTabComponentAt(i);}if(c instanceof JLabel l)style(l,i==t.getSelectedIndex(),false);}t.revalidate();t.repaint();}
 private static void style(JLabel l,boolean active,boolean hover){Color border=active?Theme.accent():(hover?Theme.text():Theme.border());l.setForeground(active?Theme.text():Theme.muted());l.setBackground(hover&&!active?Theme.panel():Theme.panel2());l.setBorder(new CompoundBorder(new LineBorder(border,1,true),new EmptyBorder(0,HPAD-1,0,HPAD-1)));}
 private static final class CanonicalUI extends BasicTabbedPaneUI{protected Insets getTabAreaInsets(int p){return new Insets(0,0,3,0);}protected Insets getContentBorderInsets(int p){return new Insets(0,0,0,0);}protected void paintContentBorder(Graphics g,int p,int i){}protected void paintFocusIndicator(Graphics g,int p,Rectangle[]r,int i,Rectangle ir,Rectangle tr,boolean s){}protected void paintTabBackground(Graphics g,int p,int i,int x,int y,int w,int h,boolean s){}protected void paintTabBorder(Graphics g,int p,int i,int x,int y,int w,int h,boolean s){}protected int calculateTabAreaHeight(int p,int rc,int mh){return TAB_H+4;}protected int getTabRunOverlay(int p){return 0;}}
 private NorthStarTabs(){}
}
