package com.wtm.ui;

import javax.swing.*;import javax.swing.border.*;import java.awt.*;import java.awt.event.*;import java.io.File;import java.nio.file.*;import java.util.*;

/** User-facing picker restricted to the signed-in user's normal folders. */
public final class NorthStarFileDialog{
 public static Path open(Component owner,String title,String...ext){return show(owner,title,false,null,ext);}public static Path save(Component owner,String title,String filename){return show(owner,title,true,filename);}
 private static Path show(Component owner,String title,boolean save,String filename,String...ext){Path home=Path.of(System.getProperty("user.home")).toAbsolutePath().normalize(),downloads=home.resolve("Downloads");final Path[]dir={Files.isDirectory(downloads)?downloads:home},result={null};Window w=SwingUtilities.getWindowAncestor(owner);JDialog d=new JDialog(w,title,Dialog.ModalityType.APPLICATION_MODAL);d.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);d.setSize(900,610);d.setMinimumSize(new Dimension(760,500));d.setLocationRelativeTo(owner);JPanel root=new JPanel(new BorderLayout(12,12));root.setBackground(Theme.bg());root.setBorder(new EmptyBorder(16,16,16,16));d.setContentPane(root);JLabel current=new JLabel();current.setForeground(Theme.muted());DefaultListModel<File>model=new DefaultListModel<>();JList<File>list=new JList<>(model);list.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);list.setFixedCellHeight(34);list.setCellRenderer((l,v,i,s,f)->{JLabel x=new JLabel((v.isDirectory()?"▣   ":"    ")+v.getName());x.setOpaque(true);x.setBorder(new EmptyBorder(6,10,6,10));x.setBackground(s?Theme.accent():Theme.panel());x.setForeground(s?Color.WHITE:Theme.text());return x;});Runnable load=()->{model.clear();Path rel;try{rel=home.relativize(dir[0]);}catch(Exception e){rel=dir[0];}current.setText(rel.toString().isBlank()?"Home":"Home / "+rel);File[]fs=dir[0].toFile().listFiles();if(fs==null)return;Arrays.sort(fs,Comparator.comparing(File::isFile).thenComparing(f->f.getName().toLowerCase(Locale.ROOT)));for(File f:fs){if(f.isHidden()||f.getName().startsWith("."))continue;if(f.isDirectory())model.addElement(f);else if(save||ext.length==0||matches(f,ext))model.addElement(f);}};
 JPanel quick=new JPanel();quick.setOpaque(false);quick.setLayout(new BoxLayout(quick,BoxLayout.Y_AXIS));quick.setBorder(new CompoundBorder(new LineBorder(Theme.border()),new EmptyBorder(10,8,10,8)));quick.setPreferredSize(new Dimension(155,100));JLabel qh=new JLabel("QUICK ACCESS");qh.setForeground(Theme.muted());qh.setFont(new Font(Font.SANS_SERIF,Font.BOLD,11));quick.add(qh);quick.add(Box.createVerticalStrut(8));addQuick(quick,"Downloads",home.resolve("Downloads"),dir,load);addQuick(quick,"Desktop",home.resolve("Desktop"),dir,load);addQuick(quick,"Documents",home.resolve("Documents"),dir,load);addQuick(quick,"Home",home,dir,load);
 JPanel top=new JPanel(new BorderLayout(8,0));top.setOpaque(false);JButton up=new JButton("↑ Up");up.addActionListener(e->{Path p=dir[0].getParent();if(p!=null&&p.normalize().startsWith(home)&&!dir[0].equals(home)){dir[0]=p;load.run();}});top.add(up,BorderLayout.WEST);top.add(current);root.add(top,BorderLayout.NORTH);JScrollPane sp=new JScrollPane(list);sp.setBorder(new LineBorder(Theme.border()));JPanel center=new JPanel(new BorderLayout(10,0));center.setOpaque(false);center.add(quick,BorderLayout.WEST);center.add(sp);root.add(center);JTextField name=new JTextField(filename==null?"":filename);JPanel bottom=new JPanel(new BorderLayout(8,8));bottom.setOpaque(false);if(save){JPanel np=new JPanel(new BorderLayout(8,0));np.setOpaque(false);JLabel nl=new JLabel("File name");nl.setForeground(Theme.text());np.add(nl,BorderLayout.WEST);np.add(name);bottom.add(np,BorderLayout.NORTH);}JPanel acts=new JPanel(new FlowLayout(FlowLayout.RIGHT,8,0));acts.setOpaque(false);JButton cancel=new JButton("Cancel"),ok=new JButton(save?"Save":"Open");acts.add(cancel);acts.add(ok);bottom.add(acts,BorderLayout.SOUTH);root.add(bottom,BorderLayout.SOUTH);Runnable choose=()->{File f=list.getSelectedValue();if(!save&&f!=null&&f.isDirectory()){Path p=f.toPath().toAbsolutePath().normalize();if(p.startsWith(home)){dir[0]=p;load.run();}return;}Path p;if(save){String n=name.getText().trim();if(n.isBlank())return;p=dir[0].resolve(n).normalize();}else{if(f==null||f.isDirectory())return;p=f.toPath().toAbsolutePath().normalize();}if(!p.startsWith(home))return;result[0]=p;d.dispose();};list.addMouseListener(new MouseAdapter(){public void mouseClicked(MouseEvent e){if(e.getClickCount()==2)choose.run();}});ok.addActionListener(e->choose.run());cancel.addActionListener(e->d.dispose());load.run();NorthStarThemeCompliance.apply(root);d.getRootPane().setDefaultButton(ok);d.setVisible(true);return result[0];}
 private static void addQuick(JPanel p,String label,Path target,Path[]dir,Runnable load){if(!Files.isDirectory(target))return;JButton b=new JButton(label);b.setHorizontalAlignment(SwingConstants.LEFT);b.setMaximumSize(new Dimension(Integer.MAX_VALUE,32));b.setPreferredSize(new Dimension(135,32));b.setAlignmentX(Component.LEFT_ALIGNMENT);b.addActionListener(e->{dir[0]=target;load.run();});p.add(b);p.add(Box.createVerticalStrut(4));}
 private static boolean matches(File f,String[]ext){String n=f.getName().toLowerCase(Locale.ROOT);for(String e:ext){String x=e.toLowerCase(Locale.ROOT);if(!x.startsWith("."))x="."+x;if(n.endsWith(x))return true;}return false;}private NorthStarFileDialog(){}
}
