package com.wtm.ui;
import com.wtm.config.AppConfig;import com.wtm.firstparty.*;import com.wtm.map.TileMapPanel;import com.wtm.net.HttpService;import com.wtm.util.MiniJson;
import javax.swing.*;import javax.swing.border.EmptyBorder;import javax.swing.table.DefaultTableModel;import java.awt.*;import java.awt.event.*;import java.lang.reflect.*;import java.net.URLEncoder;import java.nio.charset.StandardCharsets;import java.time.LocalDateTime;import java.util.*;import java.util.List;

public final class TruckTrackingModernizer {
 private static final String[] CATS={"Home / Origin","Logistics Center","Dealer","Carrier Terminal","Supplier","Cross-Dock / Consolidation Point","Service / Support Facility","Other / Temporary Destination"};
 private TruckTrackingModernizer(){}
 public static void start(){javax.swing.Timer t=new javax.swing.Timer(900,e->scan());t.setInitialDelay(1200);t.start();}
 private static void scan(){for(Window w:Window.getWindows())if(w instanceof JFrame f&&f.isDisplayable())walk(f);}
 private static void walk(Container c){for(Component x:c.getComponents()){if(x.getClass().getName().equals("com.wtm.ui.TruckTrackingPanel"))modernize((JPanel)x);if(x instanceof Container ct)walk(ct);}}
 private static void modernize(JPanel panel){if(Boolean.TRUE.equals(panel.getClientProperty("northstar.firstparty.tracking")))return;JTabbedPane tabs=findTabs(panel);if(tabs==null)return;panel.putClientProperty("northstar.firstparty.tracking",Boolean.TRUE);AppConfig cfg=config(panel);if(cfg!=null){cfg.showTrak4OnMap=false;cfg.trak4Mode="DISABLED";}
   for(int i=tabs.getTabCount()-1;i>=0;i--){String s=tabs.getTitleAt(i);if(s!=null&&s.toLowerCase().contains("trak-4"))tabs.removeTabAt(i);}
   replacePlayback(tabs,cfg);
   tabs.addTab("Tracker Devices",trackerPanel());tabs.addTab("Assignments & Trips",tripsPanel());tabs.addTab("Logistics Network",networkPanel());
   tabs.revalidate();tabs.repaint();
 }
 private static AppConfig config(JPanel p){try{Field f=p.getClass().getDeclaredField("config");f.setAccessible(true);return (AppConfig)f.get(p);}catch(Exception e){return null;}}
 private static JTabbedPane findTabs(Container r){for(Component c:r.getComponents()){if(c instanceof JTabbedPane t)return t;if(c instanceof Container ct){JTabbedPane t=findTabs(ct);if(t!=null)return t;}}return null;}
 private static void replacePlayback(JTabbedPane tabs,AppConfig cfg){for(int i=0;i<tabs.getTabCount();i++){String s=tabs.getTitleAt(i);if(s!=null&&s.toLowerCase().contains("playback")){Component old=tabs.getComponentAt(i);JPanel root=new JPanel(new BorderLayout(0,8));root.setBackground(Theme.bg());JPanel top=new JPanel(new BorderLayout());top.setOpaque(false);top.add(old);JComponent map=buildMap(cfg);JSplitPane split=new JSplitPane(JSplitPane.VERTICAL_SPLIT,top,map);split.setResizeWeight(.38);split.setDividerSize(7);split.setBorder(null);root.add(split);tabs.setComponentAt(i,root);tabs.setTitleAt(i,"Playback / Live Map");return;}}}
 private static JComponent buildMap(AppConfig original){if(original==null)return note("Map unavailable until Truck Tracking configuration is loaded.");try{AppConfig c=new AppConfig();c.primary=original.primary;c.tomTomApiKey=original.tomTomApiKey;c.showTraffic=original.showTraffic;c.showRadar=false;c.showAlertsOnMap=false;c.showFedexTrucksOnMap=original.showFedexTrucksOnMap;c.showStarhubTrucksOnMap=original.showStarhubTrucksOnMap;c.showTrak4OnMap=false;c.truckDeliveredMapDays=original.truckDeliveredMapDays;c.monitored.clear();c.routes.clear();TileMapPanel base=new TileMapPanel(c,new HttpService());return new NetworkTrackerMap(base);}catch(Exception ex){return note("Live map could not initialize: "+ex.getMessage());}}
 private static JComponent note(String s){JTextArea a=new JTextArea(s);a.setEditable(false);a.setLineWrap(true);a.setWrapStyleWord(true);return a;}
 private static JPanel trackerPanel(){JPanel p=page();DefaultTableModel m=new DefaultTableModel(new Object[]{"Tracker","Hardware ID","IMEI","Status","Battery","Signal","Last Seen","Assigned Trailer"},0);JTable t=new JTable(m);Runnable refresh=()->{m.setRowCount(0);for(TrackerDevice d:TrackerRegistryStore.get().all()){TrackerTrip tr=TrackerTripStore.get().activeForDevice(d.id());m.addRow(new Object[]{d.display(),d.hardwareId(),d.imei(),d.status(),String.format("%.0f%%",d.batteryPct()),d.signal(),d.lastSeen(),tr==null?"":tr.trailerId()});}};refresh.run();JPanel a=actions();JButton add=new JButton("Add Tracker");JButton tele=new JButton("Import Telemetry CSV");JButton refreshB=new JButton("Refresh");a.add(add);a.add(tele);a.add(refreshB);p.add(a,BorderLayout.NORTH);p.add(new JScrollPane(t),BorderLayout.CENTER);p.add(help("First-party tracker registry. Future cellular devices can post the same telemetry fields: DeviceId, Timestamp, Latitude, Longitude, SpeedMph, BatteryPct, Signal. Imported telemetry immediately updates the assigned trailer and dashboard truck position."),BorderLayout.SOUTH);add.addActionListener(e->{JTextField id=new JTextField(),hw=new JTextField(),imei=new JTextField(),label=new JTextField();Object[] msg={"Tracker ID",id,"Label",label,"Hardware ID",hw,"IMEI / modem ID",imei};if(JOptionPane.showConfirmDialog(p,msg,"Add NorthStar Tracker",JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION&&!id.getText().isBlank()){TrackerRegistryStore.get().upsert(new TrackerDevice(id.getText().trim(),hw.getText().trim(),imei.getText().trim(),label.getText().trim(),"READY",100,0,"",Double.NaN,Double.NaN,"",""));refresh.run();}});tele.addActionListener(e->{JFileChooser fc=new JFileChooser();if(fc.showOpenDialog(p)==JFileChooser.APPROVE_OPTION)try{int n=TrackerTelemetryStore.get().importCsv(fc.getSelectedFile().toPath());JOptionPane.showMessageDialog(p,"Imported "+n+" telemetry points.");refresh.run();}catch(Exception ex){error(p,ex);}});refreshB.addActionListener(e->refresh.run());return p;}
 private static JPanel tripsPanel(){JPanel p=page();DefaultTableModel m=new DefaultTableModel(new Object[]{"Tracker","Trailer ID","Shipment ID","Destination","State","Assigned","ETA","Delay"},0);JTable t=new JTable(m);Runnable refresh=()->{m.setRowCount(0);for(TrackerTrip tr:TrackerTripStore.get().all()){NetworkLocation n=NetworkLocationStore.get().find(tr.destinationId());m.addRow(new Object[]{tr.deviceId(),tr.trailerId(),tr.shipmentId(),n==null?tr.destinationId():n.name(),tr.state(),tr.assignedAt(),tr.estimatedArrival(),tr.delayMinutes()+" min"});}};refresh.run();JPanel a=actions();JButton assign=new JButton("Assign Tracker to Trailer");JButton refreshB=new JButton("Refresh");a.add(assign);a.add(refreshB);p.add(a,BorderLayout.NORTH);p.add(new JScrollPane(t),BorderLayout.CENTER);p.add(help("Automatic lifecycle is prepared as: ASSIGNED → OUTBOUND IN TRANSIT → ARRIVED AT DESTINATION → DELIVERED / RETURNING → RETURNED TO TUSCALOOSA. Destination and home geofences drive the transitions as tracker telemetry arrives."),BorderLayout.SOUTH);assign.addActionListener(e->{List<TrackerDevice> ds=TrackerRegistryStore.get().all();List<NetworkLocation> ns=NetworkLocationStore.get().all().stream().filter(NetworkLocation::active).toList();if(ds.isEmpty()||ns.isEmpty()){JOptionPane.showMessageDialog(p,"Add at least one tracker and one Logistics Network location first.");return;}JComboBox<TrackerDevice> dev=new JComboBox<>(ds.toArray(TrackerDevice[]::new));JComboBox<NetworkLocation> dest=new JComboBox<>(ns.toArray(NetworkLocation[]::new));dev.setRenderer(new DefaultListCellRenderer(){public Component getListCellRendererComponent(JList<?> l,Object v,int i,boolean s,boolean f){super.getListCellRendererComponent(l,v,i,s,f);setText(v instanceof TrackerDevice d?d.display():String.valueOf(v));return this;}});dest.setRenderer(new DefaultListCellRenderer(){public Component getListCellRendererComponent(JList<?> l,Object v,int i,boolean s,boolean f){super.getListCellRendererComponent(l,v,i,s,f);setText(v instanceof NetworkLocation n?n.display():String.valueOf(v));return this;}});JTextField trailer=new JTextField(),ship=new JTextField(),eta=new JTextField();Object[] msg={"Tracker",dev,"Trailer ID",trailer,"Outbound Shipment ID (optional)",ship,"Destination",dest,"Scheduled arrival (optional)",eta};if(JOptionPane.showConfirmDialog(p,msg,"Assign Tracker",JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION&&!trailer.getText().isBlank()){TrackerDevice d=(TrackerDevice)dev.getSelectedItem();NetworkLocation n=(NetworkLocation)dest.getSelectedItem();TrackerTrip tr=new TrackerTrip(UUID.randomUUID().toString(),d.id(),trailer.getText().trim(),ship.getText().trim(),n.id(),"ASSIGNED",LocalDateTime.now().toString(),eta.getText().trim(),eta.getText().trim(),0,LocalDateTime.now().toString(),"");TrackerTripStore.get().upsert(tr);refresh.run();}});refreshB.addActionListener(e->refresh.run());return p;}
 private static JPanel networkPanel(){JPanel p=page();DefaultTableModel m=new DefaultTableModel(new Object[]{"Name","Category","Address","Network / Dealer ID","Latitude","Longitude","Geofence","Active"},0);JTable t=new JTable(m);Runnable refresh=()->{m.setRowCount(0);for(NetworkLocation n:NetworkLocationStore.get().all())m.addRow(new Object[]{n.name(),n.category(),n.address(),n.externalId(),n.hasCoordinates()?n.latitude():"",n.hasCoordinates()?n.longitude():"",n.geofenceMeters()+" m",n.active()});};refresh.run();JPanel a=actions();JButton add=new JButton("Add Location / Address Lookup"),imp=new JButton("Import Dealers CSV"),templ=new JButton("Dealer CSV Template"),geo=new JButton("Geocode Missing"),del=new JButton("Delete");a.add(add);a.add(imp);a.add(templ);a.add(geo);a.add(del);p.add(a,BorderLayout.NORTH);p.add(new JScrollPane(t),BorderLayout.CENTER);p.add(help("Logistics Network locations are separate from Weather / Commute pins. Categories control pin styling and geofence behavior. Dealer CSV supports dealer number / CustomerBK plus street address; coordinates can be generated from addresses."),BorderLayout.SOUTH);add.addActionListener(e->addNetwork(p,refresh));imp.addActionListener(e->{JFileChooser fc=new JFileChooser();if(fc.showOpenDialog(p)==JFileChooser.APPROVE_OPTION)try{int n=NetworkLocationStore.get().importCsv(fc.getSelectedFile().toPath());JOptionPane.showMessageDialog(p,"Imported "+n+" network/dealer locations.");refresh.run();}catch(Exception ex){error(p,ex);}});templ.addActionListener(e->{JFileChooser fc=new JFileChooser();fc.setSelectedFile(new java.io.File("northstar-dealer-network-template.csv"));if(fc.showSaveDialog(p)==JFileChooser.APPROVE_OPTION)try{NetworkLocationStore.get().exportTemplate(fc.getSelectedFile().toPath());}catch(Exception ex){error(p,ex);}});geo.addActionListener(e->bulkGeocode(p,refresh));del.addActionListener(e->{int r=t.getSelectedRow();if(r<0)return;String name=String.valueOf(m.getValueAt(r,0));for(NetworkLocation n:NetworkLocationStore.get().all())if(n.name().equals(name)){NetworkLocationStore.get().delete(n.id());break;}refresh.run();});return p;}
 private static void addNetwork(Component owner,Runnable refresh){JTextField name=new JTextField(),addr=new JTextField(),ext=new JTextField(),gf=new JTextField("500");JComboBox<String> cat=new JComboBox<>(CATS);Object[] msg={"Name",name,"Category",cat,"Street address / city",addr,"Dealer / network ID (optional)",ext,"Geofence meters",gf};if(JOptionPane.showConfirmDialog(owner,msg,"Add Logistics Network Location",JOptionPane.OK_CANCEL_OPTION)!=JOptionPane.OK_OPTION||name.getText().isBlank())return;double[] ll=geocodeOne(addr.getText().trim());int g=500;try{g=Integer.parseInt(gf.getText().trim());}catch(Exception ignored){}NetworkLocation n=new NetworkLocation(UUID.randomUUID().toString(),name.getText().trim(),String.valueOf(cat.getSelectedItem()),addr.getText().trim(),ext.getText().trim(),ll[0],ll[1],g,"",true);NetworkLocationStore.get().upsert(n);if(!Double.isFinite(ll[0]))JOptionPane.showMessageDialog(owner,"Location saved, but the address could not be geocoded. You can retry with Geocode Missing.");refresh.run();}
 private static void bulkGeocode(Component owner,Runnable refresh){List<NetworkLocation> missing=NetworkLocationStore.get().all().stream().filter(n->!n.hasCoordinates()&&!n.address().isBlank()).toList();if(missing.isEmpty()){JOptionPane.showMessageDialog(owner,"No locations are missing coordinates.");return;}new SwingWorker<Integer,Void>(){protected Integer doInBackground(){int n=0;for(NetworkLocation x:missing){double[] ll=geocodeOne(x.address());if(Double.isFinite(ll[0])){NetworkLocationStore.get().upsert(new NetworkLocation(x.id(),x.name(),x.category(),x.address(),x.externalId(),ll[0],ll[1],x.geofenceMeters(),x.notes(),x.active()));n++;}try{Thread.sleep(1100);}catch(InterruptedException e){Thread.currentThread().interrupt();break;}}return n;}protected void done(){try{JOptionPane.showMessageDialog(owner,"Geocoded "+get()+" of "+missing.size()+" locations.");}catch(Exception ex){error(owner,ex);}refresh.run();}}.execute();}
 private static double[] geocodeOne(String address){if(address==null||address.isBlank())return new double[]{Double.NaN,Double.NaN};try{String url="https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&q="+URLEncoder.encode(address,StandardCharsets.UTF_8);String body=new HttpService().getText(url);List<Object> a=MiniJson.arr(MiniJson.parse(body));if(a.isEmpty())return new double[]{Double.NaN,Double.NaN};Map<String,Object> o=MiniJson.obj(a.get(0));return new double[]{Double.parseDouble(MiniJson.str(o.get("lat"))),Double.parseDouble(MiniJson.str(o.get("lon")))};}catch(Exception e){return new double[]{Double.NaN,Double.NaN};}}
 private static JPanel page(){JPanel p=new JPanel(new BorderLayout(8,8));p.setBackground(Theme.bg());p.setBorder(new EmptyBorder(10,10,10,10));return p;}private static JPanel actions(){JPanel p=new JPanel(new FlowLayout(FlowLayout.LEFT,7,0));p.setOpaque(false);return p;}private static JTextArea help(String s){JTextArea a=new JTextArea(s);a.setEditable(false);a.setLineWrap(true);a.setWrapStyleWord(true);a.setOpaque(false);a.setForeground(Theme.muted());a.setBorder(new EmptyBorder(8,2,0,2));return a;}private static void error(Component c,Exception e){JOptionPane.showMessageDialog(c,e.getMessage(),"NorthStar Truck Tracking",JOptionPane.ERROR_MESSAGE);}
 private static final class NetworkTrackerMap extends JLayeredPane {
   final TileMapPanel base; final Overlay overlay;
   NetworkTrackerMap(TileMapPanel b){base=b;overlay=new Overlay(b);setPreferredSize(new Dimension(900,420));add(base,Integer.valueOf(0));add(overlay,Integer.valueOf(100));addComponentListener(new ComponentAdapter(){public void componentResized(ComponentEvent e){base.setBounds(0,0,getWidth(),getHeight());overlay.setBounds(0,0,getWidth(),getHeight());}});javax.swing.Timer t=new javax.swing.Timer(1200,e->overlay.repaint());t.start();}
 }
 private static final class Overlay extends JComponent {final TileMapPanel map;Overlay(TileMapPanel m){map=m;setOpaque(false);}protected void paintComponent(Graphics g0){Graphics2D g=(Graphics2D)g0.create();g.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);try{double lat=(double)field(map,"centerLat"),lon=(double)field(map,"centerLon");int z=(int)field(map,"zoom");for(NetworkLocation n:NetworkLocationStore.get().all())if(n.active()&&n.hasCoordinates()){Point p=point(n.latitude(),n.longitude(),lat,lon,z,getWidth(),getHeight());drawPin(g,p,n.category(),n.name());}for(TrackerDevice d:TrackerRegistryStore.get().all())if(Double.isFinite(d.latitude())&&Double.isFinite(d.longitude())){Point p=point(d.latitude(),d.longitude(),lat,lon,z,getWidth(),getHeight());g.setColor(new Color(0,200,160));g.fillOval(p.x-7,p.y-7,14,14);g.setColor(Color.WHITE);g.drawOval(p.x-7,p.y-7,14,14);g.drawString(d.label()==null||d.label().isBlank()?d.id():d.label(),p.x+10,p.y-8);}}catch(Exception ignored){}g.dispose();}
   static Object field(Object o,String n)throws Exception{Field f=o.getClass().getDeclaredField(n);f.setAccessible(true);return f.get(o);}static Point point(double lat,double lon,double clat,double clon,int z,int w,int h){double scale=256*Math.pow(2,z),wx=(lon+180)/360*scale, cx=(clon+180)/360*scale;double wy=(1-Math.log(Math.tan(Math.toRadians(lat))+1/Math.cos(Math.toRadians(lat)))/Math.PI)/2*scale,cy=(1-Math.log(Math.tan(Math.toRadians(clat))+1/Math.cos(Math.toRadians(clat)))/Math.PI)/2*scale;return new Point((int)(w/2+wx-cx),(int)(h/2+wy-cy));}
   static void drawPin(Graphics2D g,Point p,String cat,String name){Color c=cat.equalsIgnoreCase("Dealer")?new Color(120,90,255):cat.equalsIgnoreCase("Logistics Center")||cat.equalsIgnoreCase("Home / Origin")?new Color(0,160,230):new Color(235,170,40);g.setColor(c);if(cat.equalsIgnoreCase("Dealer")){g.fillOval(p.x-6,p.y-6,12,12);}else{g.fillRoundRect(p.x-7,p.y-7,14,14,4,4);}g.setColor(Color.WHITE);g.drawString(name,p.x+10,p.y-8);}
 }
}
