package com.wtm.ui;
import com.wtm.config.AppConfig;import com.wtm.firstparty.*;import com.wtm.map.TileMapPanel;import com.wtm.net.HttpService;
import javax.swing.*;import java.awt.*;import java.awt.event.*;import java.lang.reflect.*;import java.util.*;import java.util.regex.*;
public final class TruckTrackingPolishInjector{
 private TruckTrackingPolishInjector(){}public static void start(){javax.swing.Timer t=new javax.swing.Timer(650,e->scan());t.setInitialDelay(1800);t.start();}
 private static void scan(){for(Window w:Window.getWindows())if(w instanceof JFrame f&&f.isDisplayable())walk(f);}
 private static void walk(Container c){for(Component x:c.getComponents()){if(x.getClass().getName().equals("com.wtm.ui.TruckTrackingPanel"))polish((JPanel)x);if(x instanceof Container ct)walk(ct);}}
 private static void polish(JPanel p){JTabbedPane tabs=findTruckTabs(p);if(tabs==null)return;for(int i=tabs.getTabCount()-1;i>=0;i--){String s=tabs.getTitleAt(i);if(s!=null&&(s.equalsIgnoreCase("Logistics Network")||s.toLowerCase().contains("trak-4")||s.toLowerCase().contains("trak 4")))tabs.removeTabAt(i);}if(p.getClientProperty("northstar.truck.playback187")==null){fixPlayback(p,tabs);p.putClientProperty("northstar.truck.playback187",Boolean.TRUE);}NorthStarTabs.refreshHeaders(tabs);NorthStarThemeCompliance.apply(p);p.setBackground(Theme.bg());p.revalidate();p.repaint();}
 private static JTabbedPane findTruckTabs(Container r){for(Component c:r.getComponents()){if(c instanceof JTabbedPane t){for(int i=0;i<t.getTabCount();i++)if("Current".equalsIgnoreCase(t.getTitleAt(i)))return t;}if(c instanceof Container ct){JTabbedPane t=findTruckTabs(ct);if(t!=null)return t;}}return null;}
 private static void fixPlayback(JPanel p,JTabbedPane tabs){for(int i=0;i<tabs.getTabCount();i++){String s=tabs.getTitleAt(i);if(s==null||!s.toLowerCase().contains("playback"))continue;Component current=tabs.getComponentAt(i);Component settings=current;if(current instanceof JPanel cp&&cp.getComponentCount()==1&&cp.getComponent(0)instanceof JSplitPane sp)settings=sp.getTopComponent();else if(current instanceof JPanel cp){for(Component x:cp.getComponents())if(!(x instanceof TileMapPanel)&&!(x instanceof JLayeredPane)){settings=x;break;}}JPanel root=new JPanel(new BorderLayout(0,8));root.setBackground(Theme.bg());JScrollPane ss=new JScrollPane(settings);ss.setBorder(null);ss.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);ss.setPreferredSize(new Dimension(900,300));ss.getVerticalScrollBar().setUnitIncrement(18);root.add(ss,BorderLayout.NORTH);root.add(map(config(p),settings),BorderLayout.CENTER);tabs.setComponentAt(i,root);tabs.setTitleAt(i,"Playback / Live Map");return;}}
 private static AppConfig config(JPanel p){try{Field f=p.getClass().getDeclaredField("config");f.setAccessible(true);return(AppConfig)f.get(p);}catch(Exception e){return null;}}
 private static JComponent map(AppConfig o,Component settings){if(o==null)return note("Live map unavailable until Truck Tracking configuration is loaded.");try{AppConfig c=new AppConfig();c.primary=o.primary;c.tomTomApiKey=o.tomTomApiKey;c.showTraffic=o.showTraffic;c.showRadar=false;c.showAlertsOnMap=false;c.showFedexTrucksOnMap=o.showFedexTrucksOnMap;c.showStarhubTrucksOnMap=o.showStarhubTrucksOnMap;c.showTrak4OnMap=false;c.monitored.clear();c.routes.clear();TileMapPanel b=new TileMapPanel(c,new HttpService());return new StyledMap(b,settings);}catch(Exception e){return note("Live map could not initialize: "+e.getMessage());}}
 private static JComponent note(String s){JTextArea a=new JTextArea(s);a.setEditable(false);a.setForeground(Theme.text());a.setBackground(Theme.panel());return a;}
 private static final class StyledMap extends JLayeredPane{final TileMapPanel base;final Overlay over;StyledMap(TileMapPanel b,Component settings){base=b;over=new Overlay(b,settings);setBackground(Theme.panel());setOpaque(true);setPreferredSize(new Dimension(1000,560));add(base,Integer.valueOf(0));add(over,Integer.valueOf(100));addComponentListener(new ComponentAdapter(){public void componentResized(ComponentEvent e){base.setBounds(0,0,getWidth(),getHeight());over.setBounds(0,0,getWidth(),getHeight());}});javax.swing.Timer t=new javax.swing.Timer(850,e->over.repaint());t.start();}}
 private static final class Overlay extends JComponent{final TileMapPanel map;final Component settings;Overlay(TileMapPanel m,Component s){map=m;settings=s;setOpaque(false);}protected void paintComponent(Graphics g0){Graphics2D g=(Graphics2D)g0.create();NetworkOverlayPainter.paint(g,map,getWidth(),getHeight(),true,forced(settings));for(TrackerDevice d:TrackerRegistryStore.get().all())try{if(Double.isFinite(d.latitude())&&Double.isFinite(d.longitude())){double lat=(double)field(map,"centerLat"),lon=(double)field(map,"centerLon");int z=(int)field(map,"zoom");Point p=NetworkOverlayPainter.point(d.latitude(),d.longitude(),lat,lon,z,getWidth(),getHeight());g.setColor(Theme.good());g.fillOval(p.x-7,p.y-7,14,14);g.setColor(Theme.text());g.drawString(d.display(),p.x+10,p.y-8);}}catch(Exception ignored){}g.dispose();}
  private static Set<String>forced(Component c){Set<String>out=new LinkedHashSet<>();walk(c,out);return out;}private static void walk(Component c,Set<String>o){if(c instanceof JComboBox<?> b){Object x=b.getSelectedItem();if(x!=null)parse(String.valueOf(x),o);}if(c instanceof Container ct)for(Component x:ct.getComponents())walk(x,o);}private static void parse(String s,Set<String>o){Matcher m=Pattern.compile("(?:origin|destination)=([^,}]+)",Pattern.CASE_INSENSITIVE).matcher(s);while(m.find())o.add(m.group(1).trim());}private static Object field(Object o,String n)throws Exception{Field f=o.getClass().getDeclaredField(n);f.setAccessible(true);return f.get(o);}}
}
