package com.wtm.ui;
import javax.swing.*;import javax.swing.border.LineBorder;import java.awt.*;import java.lang.reflect.*;import java.util.*;
/** Enforces the NorthStar navigation/tab/theme contract across native and injected workspaces. */
public final class UiConsistencyInjector{
 private UiConsistencyInjector(){}
 public static void start(){javax.swing.Timer t=new javax.swing.Timer(350,e->scan());t.setInitialDelay(250);t.start();}
 private static void scan(){for(Window w:Window.getWindows())if(w.isDisplayable()){if(w instanceof JDialog)NorthStarThemeCompliance.apply(w);if(w instanceof JFrame f&&f.getClass().getName().equals("com.wtm.ui.OperationsWorkspaceFrame"))fixSidebar(f);walk(w);}}
 private static void walk(Container c){for(Component x:c.getComponents()){if(x instanceof JTabbedPane t)NorthStarTabs.refreshHeaders(t);if(x instanceof NorthStarTabHost h)h.refreshStyle();if(x instanceof JScrollPane sp){sp.getViewport().setBackground(Theme.panel());sp.setBorder(new LineBorder(Theme.border()));}if(x instanceof JTable tb){tb.setBackground(Theme.panel());tb.setForeground(Theme.text());tb.setGridColor(Theme.border());tb.getTableHeader().setBackground(Theme.panel2());tb.getTableHeader().setForeground(Theme.text());}if(x instanceof Container ct)walk(ct);}}
 @SuppressWarnings("unchecked") private static void fixSidebar(JFrame f){try{Field mf=f.getClass().getDeclaredField("sidebarRouteButtons");mf.setAccessible(true);Map<String,JButton> map=(Map<String,JButton>)mf.get(f);Field af=f.getClass().getDeclaredField("activeWorkspaceRoute");af.setAccessible(true);String active=String.valueOf(af.get(f));for(var e:map.entrySet()){JButton b=e.getValue();boolean on=e.getKey().equalsIgnoreCase(active);b.putClientProperty("northstar.sidebar.active",on);b.setForeground(on?Color.WHITE:Theme.muted());b.setFont(new Font(Font.SANS_SERIF,on?Font.BOLD:Font.PLAIN,12));b.setPreferredSize(new Dimension(180,42));b.setMinimumSize(new Dimension(120,42));b.setMaximumSize(new Dimension(Integer.MAX_VALUE,42));b.repaint();}JButton ai=map.get("NorthStar Intelligence"),dc=map.get("Data Collection");JPanel side=sidebarPanel(f);if(side!=null&&ai!=null&&dc!=null)normalizeInjectedOrder(side,ai,dc);}catch(Exception ignored){}}
 private static JPanel sidebarPanel(Container c){for(Component x:c.getComponents()){if(x instanceof JScrollPane sp&&sp.getViewport().getView() instanceof JPanel p&&containsButton(p,"Dashboard"))return p;if(x instanceof Container ct){JPanel p=sidebarPanel(ct);if(p!=null)return p;}}return null;}
 private static boolean containsButton(Container c,String text){for(Component x:c.getComponents()){if(x instanceof JButton b&&strip(b.getText()).equalsIgnoreCase(text))return true;if(x instanceof Container ct&&containsButton(ct,text))return true;}return false;}
 private static String strip(String s){return s==null?"":s.replaceAll("^[^A-Za-z0-9]+\\s*","").trim();}
 private static void normalizeInjectedOrder(JPanel side,JButton ai,JButton dc){int admin=-1;for(int i=0;i<side.getComponentCount();i++)if(side.getComponent(i) instanceof JLabel l&&"ADMINISTRATION".equalsIgnoreCase(l.getText())){admin=i;break;}if(admin<0)return;side.remove(ai);side.remove(dc);admin=-1;for(int i=0;i<side.getComponentCount();i++)if(side.getComponent(i) instanceof JLabel l&&"ADMINISTRATION".equalsIgnoreCase(l.getText())){admin=i;break;}if(admin<0)return;int filler=admin;while(filler>0&&side.getComponent(filler-1) instanceof Box.Filler)filler--;side.add(ai,filler);side.add(dc,filler+1);side.revalidate();side.repaint();}
}
