package com.wtm.importer;
import com.wtm.config.ConfigService; import java.io.*; import java.nio.charset.StandardCharsets; import java.nio.file.*; import java.time.Instant; import java.util.*;
public final class KpiHistoryStore{
 private static final String FILE_NAME="kpi-history.csv"; private KpiHistoryStore(){}
 public static synchronized void merge(KpiImportResult result)throws IOException{Path file=ConfigService.appDataDir().resolve(FILE_NAME);Files.createDirectories(file.getParent());Map<String,String[]>records=new LinkedHashMap<>();if(Files.isRegularFile(file)){try{CsvTable t=CsvTable.read(file);for(Map<String,String>r:t.rows()){String d=r.getOrDefault("date",""),m=r.getOrDefault("metricid",""),s=r.getOrDefault("source","");if(!d.isBlank()&&!m.isBlank())records.put(d+"|"+m+"|"+s,new String[]{d,m,r.getOrDefault("label",""),r.getOrDefault("value",""),r.getOrDefault("unit",""),s,r.getOrDefault("importedat","")});}}catch(Exception ignored){}}
  String now=Instant.now().toString();for(KpiImportedMetric m:result.historyMetrics()){if(m.effectiveDate()==null)continue;String d=m.effectiveDate().toString();records.put(d+"|"+m.metricId()+"|"+m.sourceId(),new String[]{d,m.metricId(),m.label(),Double.toString(m.value()),m.unit()==null?"":m.unit(),m.sourceId(),now});}List<String>keys=new ArrayList<>(records.keySet());Collections.sort(keys);StringBuilder out=new StringBuilder("Date,MetricId,Label,Value,Unit,Source,ImportedAt\n");for(String k:keys){String[]row=records.get(k);for(int i=0;i<row.length;i++){if(i>0)out.append(',');out.append(csv(row[i]));}out.append('\n');}Files.writeString(file,out.toString(),StandardCharsets.UTF_8,StandardOpenOption.CREATE,StandardOpenOption.TRUNCATE_EXISTING);}
 public static String latestSummary(){Path file=ConfigService.appDataDir().resolve(FILE_NAME);if(!Files.isRegularFile(file))return "No KPI CSV data imported yet.";try{CsvTable t=CsvTable.read(file);Map<String,Map<String,String>>latest=new LinkedHashMap<>();for(Map<String,String>r:t.rows()){String m=r.getOrDefault("metricid",""),d=r.getOrDefault("date","");if(m.isBlank()||d.isBlank())continue;Map<String,String>o=latest.get(m);if(o==null||d.compareTo(o.getOrDefault("date",""))>0)latest.put(m,r);}if(latest.isEmpty())return "No KPI CSV data imported yet.";StringBuilder b=new StringBuilder("<html><b>Imported KPI data:</b> ");boolean first=true;for(Map<String,String>r:latest.values()){if(!first)b.append(" &nbsp; • &nbsp; ");first=false;b.append(esc(r.getOrDefault("label",r.get("metricid")))).append(" ").append(esc(r.getOrDefault("value",""))).append(esc(r.getOrDefault("unit",""))).append(" <span style='color:#8A93A3'>(").append(esc(r.getOrDefault("date",""))).append(")</span>");}return b.append("</html>").toString();}catch(Exception ex){return "KPI history is available but could not be summarized.";}}
 private static String csv(String v){v=v==null?"":v;return v.contains(",")||v.contains("\"")||v.contains("\n")?"\""+v.replace("\"","\"\"")+"\"":v;} private static String esc(String v){return v==null?"":v.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;");}
}
